// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         recipe: {
 *             agents: [{
 *                     hue: "hue",
 *                     id: "id",
 *                     label: "label",
 *                     notes: "notes"
 *                 }],
 *             data: {
 *                 kind: "composed",
 *                 scenarios: [{
 *                         count: 1,
 *                         id: "id",
 *                         kind: "adversarial",
 *                         label: "label"
 *                     }],
 *                 sources: [{
 *                         count: 1,
 *                         id: "id",
 *                         kind: "prod",
 *                         label: "label"
 *                     }]
 *             },
 *             graders: [{
 *                     id: "id",
 *                     kind: "rubric",
 *                     label: "label",
 *                     source: "proposed",
 *                     weight: "low"
 *                 }],
 *             mode: "replay",
 *             name: "name"
 *         }
 *     }
 */
export interface CreateBacktestJobRequest {
    /** Optional caller-generated key for safely retrying a mutation after an ambiguous network failure. Keys are scoped to the authenticated tenant and operation. Reusing a key with the same payload returns the original successful result; reusing it with a different payload returns 409. */
    "Idempotency-Key"?: string;
    cases?: CreateBacktestJobRequest.Cases.Item[] | null;
    evaluatorProfileId?: string | null;
    nConcurrent?: number | null;
    name: string;
    recipe: CreateBacktestJobRequest.Recipe;
}

export namespace CreateBacktestJobRequest {
    export type Cases = Cases.Item[];

    export namespace Cases {
        /**
         * One explicit case accepted by `POST /v1/backtests/jobs` for non-Dataset recipes. Dataset-backed requests use these entries only as a case-id selection; the server always loads the instruction and expected outcome from the pinned Dataset Version.
         */
        export interface Item {
            caseCluster?: (string | null) | undefined;
            caseId: string;
            expectedOutcome?: (string | null) | undefined;
            /** Required for composed recipes. Dataset-backed requests may omit it because the server loads canonical content from the pinned Version. */
            instruction?: (string | null) | undefined;
        }
    }

    export interface Recipe {
        /** 1..N agents under test. The first is treated as the comparison baseline by `BacktestResults`. */
        agents: Recipe.Agents.Item[];
        data: Recipe.Data;
        /** Optional environment the run targets. Pipeline step 03 sets this; consumers without an environment fall back to the default ephemeral sandbox. */
        environment?: (Recipe.Environment | null) | undefined;
        graders: Recipe.Graders.Item[];
        mode: Recipe.Mode;
        /** Free-text run name shown in the recipe header + top nav. */
        name: string;
        /** Optional pinned trace seed; used by the Replay preset to reproduce a single trace as the focal point of the run. */
        seed?: (string | null) | undefined;
    }

    export namespace Recipe {
        export type Agents = Agents.Item[];

        export namespace Agents {
            export interface Item {
                /** CSS color token / hex. Used by `CandidateHueDot`. */
                hue: string;
                id: string;
                label: string;
                /** Tag rendered next to the label, e.g. "current production". */
                notes: string;
                /** Defaults to `candidate`; the Results table treats the first baseline as the reference column. */
                role?: (Item.Role | null) | undefined;
            }

            export namespace Item {
                /** Defaults to `candidate`; the Results table treats the first baseline as the reference column. */
                export const Role = {
                    Baseline: "baseline",
                    Candidate: "candidate",
                } as const;
                export type Role = (typeof Role)[keyof typeof Role];
            }
        }

        export interface Data {
            /** Populated only when `kind == "dataset"`. */
            dataset?: (string | null) | undefined;
            datasetLabel?: (string | null) | undefined;
            kind: Data.Kind;
            /** Optional name the user wants to save this composed dataset as. `null` (vs absent) tells the UI the user opted out of saving. */
            savedAs?: (string | null) | undefined;
            scenarios: Data.Scenarios.Item[];
            sources: Data.Sources.Item[];
        }

        export namespace Data {
            export const Kind = {
                Composed: "composed",
                Dataset: "dataset",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
            export type Scenarios = Scenarios.Item[];

            export namespace Scenarios {
                export interface Item {
                    accepted?: (boolean | null) | undefined;
                    /** Cluster bucket emitted by the data-science layer when looking for missing scenarios in a dataset. */
                    bucket?: (Item.Bucket | null) | undefined;
                    clusterId?: (string | null) | undefined;
                    clusterLabel?: (string | null) | undefined;
                    confidence?: (number | null) | undefined;
                    count: number;
                    id: string;
                    kind: Item.Kind;
                    label: string;
                }

                export namespace Item {
                    /** Cluster bucket emitted by the data-science layer when looking for missing scenarios in a dataset. */
                    export const Bucket = {
                        Captured: "captured",
                        Adjacent: "adjacent",
                        Emerging: "emerging",
                        Edge: "edge",
                    } as const;
                    export type Bucket = (typeof Bucket)[keyof typeof Bucket];
                    export const Kind = {
                        Adversarial: "adversarial",
                        NonEnglish: "nonEnglish",
                        ToolFailure: "toolFailure",
                        LongTurn: "longTurn",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }

            export type Sources = Sources.Item[];

            export namespace Sources {
                export interface Item {
                    count: number;
                    filters?: (Item.Filters | null) | undefined;
                    id: string;
                    kind: Item.Kind;
                    label: string;
                }

                export namespace Item {
                    export interface Filters {
                        clusters?: (string[] | null) | undefined;
                        outcome?: (string | null) | undefined;
                        seed?: (string | null) | undefined;
                        window?: (string | null) | undefined;
                    }

                    export const Kind = {
                        Prod: "prod",
                        Dataset: "dataset",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }

        /**
         * Optional environment the run targets. Pipeline step 03 sets this; consumers without an environment fall back to the default ephemeral sandbox.
         */
        export interface Environment {
            /** Whether this environment is a freshly cloned ephemeral sandbox or a saved long-lived environment. */
            ephemeral?: (boolean | null) | undefined;
            id: string;
            label: string;
            snapshotId?: (string | null) | undefined;
            snapshotLabel?: (string | null) | undefined;
            /** Mirror of `SandboxRuntimeStatus` strings ("started", "stopped", …). Kept loose so callers don't need to import the environments package. */
            status?: (string | null) | undefined;
        }

        export type Graders = Graders.Item[];

        export namespace Graders {
            export interface Item {
                /** Code handler snapshot — required when `kind` is `code`. */
                code?: (Item.Code | null) | undefined;
                /** Optional human-readable explanation of why this grader was proposed. For rubric graders this doubles as the judge prompt; library scorers inline their prompt here at launch so the recipe stays self-describing. */
                evidence?: (string | null) | undefined;
                id: string;
                /** LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior. */
                judge?: (Item.Judge | null) | undefined;
                kind: Item.Kind;
                label: string;
                /** Scores at or above this value render as passing in results. */
                passThreshold?: (number | null) | undefined;
                /** Provenance: the library `Scorer.id` this grader was created from (when `source` is `library`). The prompt is snapshotted into `evidence` at launch, so editing the scorer later never mutates a past run. */
                scorerId?: (string | null) | undefined;
                /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                source: Item.Source;
                /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                weight: Item.Weight;
            }

            export namespace Item {
                /**
                 * Code handler snapshot — required when `kind` is `code`.
                 */
                export interface Code {
                    /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                    language: Code.Language;
                    source: string;
                }

                export namespace Code {
                    /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                    export const Language = {
                        Python: "python",
                        Typescript: "typescript",
                    } as const;
                    export type Language = (typeof Language)[keyof typeof Language];
                }

                /**
                 * LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior.
                 */
                export interface Judge {
                    /** Allow the judge to decline non-applicable cases; skipped cases emit no reward key instead of scoring 0. */
                    allowSkip?: boolean | undefined;
                    /** Choice→score mapping. Non-empty forces the judge to pick one choice; the mapped score is the result. */
                    choiceScores?: Judge.ChoiceScores.Item[] | undefined;
                    /** Judge model override; `None` uses the server default. */
                    model?: (string | null) | undefined;
                    /** Ask the judge to reason step-by-step before answering. */
                    useCot?: boolean | undefined;
                }

                export namespace Judge {
                    export type ChoiceScores = ChoiceScores.Item[];

                    export namespace ChoiceScores {
                        /**
                         * One judge choice mapped to a numeric score, e.g. `A → 1.0`, `B → 0.5`, `C → 0.0`. When a judge scorer declares choices, the model must pick exactly one and the mapped score is the result.
                         */
                        export interface Item {
                            label: string;
                            score: number;
                        }
                    }
                }

                export const Kind = {
                    Rubric: "rubric",
                    Classifier: "classifier",
                    Metric: "metric",
                    Embedding: "embedding",
                    Assertion: "assertion",
                    Code: "code",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
                /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                export const Source = {
                    Proposed: "proposed",
                    Library: "library",
                    Custom: "custom",
                    Dataset: "dataset",
                } as const;
                export type Source = (typeof Source)[keyof typeof Source];
                /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                export const Weight = {
                    Low: "low",
                    Med: "med",
                    High: "high",
                } as const;
                export type Weight = (typeof Weight)[keyof typeof Weight];
            }
        }

        export const Mode = {
            Replay: "replay",
            Compare: "compare",
            Regression: "regression",
            Suite: "suite",
        } as const;
        export type Mode = (typeof Mode)[keyof typeof Mode];
    }
}
