// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListBacktestJobsRequest {
    mode?: string;
    status?: string;
    limit?: number;
    offset?: number;
}
