// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "job_id"
 *     }
 */
export interface ListBacktestJobTrialsRequest {
    job_id: string;
    limit?: number;
    offset?: number;
}
