// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         event_id: "event_id",
 *         entity_type: "entity_type",
 *         entity_id: "entity_id"
 *     }
 */
export interface AddEntityRefRequest {
    event_id: string;
    entity_type: string;
    entity_id: string;
    created_by?: string;
}
