// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         source_event_id: "source_event_id",
 *         target_event_id: "target_event_id",
 *         link_type: "link_type",
 *         confidence: 1.1
 *     }
 */
export interface CreateLinkRequest {
    source_event_id: string;
    target_event_id: string;
    link_type: string;
    confidence: number;
    reasoning?: string | null;
    created_by?: string;
}
