// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         start_event_id: "start_event_id",
 *         direction: "outgoing"
 *     }
 */
export interface GraphRequest {
    start_event_id: string;
    direction: GraphRequest.Direction;
    link_types?: string[] | null;
    max_depth?: number;
    min_confidence?: number;
}

export namespace GraphRequest {
    export const Direction = {
        Outgoing: "outgoing",
        Incoming: "incoming",
        Both: "both",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
}
