// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from_entity_type: "from_entity_type",
 *         from_entity_id: "from_entity_id",
 *         to_entity_type: "to_entity_type",
 *         to_entity_id: "to_entity_id"
 *     }
 */
export interface LinkEntityRequest {
    from_entity_type: string;
    from_entity_id: string;
    to_entity_type: string;
    to_entity_id: string;
    created_by?: string;
}
