// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         scopes: ["traces:write"]
 *     }
 */
export interface CreateSdkKeyRequest {
    name: string;
    scopes: CreateSdkKeyRequest.Scopes.Item[];
}

export namespace CreateSdkKeyRequest {
    export type Scopes = Scopes.Item[];

    export namespace Scopes {
        export const Item = {
            TracesWrite: "traces:write",
            EventsRead: "events:read",
            EventsWrite: "events:write",
            UsersWrite: "users:write",
            SignalsWrite: "signals:write",
            AgentsWrite: "agents:write",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
