// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../../../../index.js";

/**
 * @example
 *     {
 *         environment_id: "environment_id",
 *         version: "version"
 *     }
 */
export interface CreateEnvironmentVersionRequest {
    /** Environment ID or slug. */
    environment_id: string;
    version: string;
    spec?: ChronicleLabsApi.EnvironmentSpec;
    status?: ChronicleLabsApi.EnvironmentVersionStatus;
}
