// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "support-sandbox",
 *         label: "Support sandbox",
 *         description: "Isolated environment for support-agent backtests."
 *     }
 */
export interface CreateEnvironmentRequest {
    slug: string;
    label: string;
    description?: string | null;
}
