// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         environment_id: "environment_id"
 *     }
 */
export interface GetEnvironmentRequest {
    /** Environment ID or slug. */
    environment_id: string;
}
