// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         session_id: "session_id"
 *     }
 */
export interface GetAgentChatSessionRequest {
    name: string;
    session_id: string;
}
