// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         runs: [{
 *                 artifactId: "artifactId",
 *                 configHash: "configHash",
 *                 operation: "generate",
 *                 runId: "runId",
 *                 schemaVersion: "schemaVersion",
 *                 startedAt: "2024-01-15T09:30:00Z",
 *                 status: "started",
 *                 toolCalls: [{
 *                         callId: "callId",
 *                         startedAt: "2024-01-15T09:30:00Z",
 *                         status: "started",
 *                         toolName: "toolName"
 *                     }]
 *             }]
 *     }
 */
export interface RecordAgentRunsRequest {
    runs: RecordAgentRunsRequest.Runs.Item[];
}

export namespace RecordAgentRunsRequest {
    export type Runs = Runs.Item[];

    export namespace Runs {
        export interface Item {
            artifactId: string;
            callOptionsHash?: (string | null) | undefined;
            configHash: string;
            durationMs?: (number | null) | undefined;
            error?: (Item.Error_ | null) | undefined;
            finishedAt?: (string | null) | undefined;
            inputHash?: (string | null) | undefined;
            operation: Item.Operation;
            preparedCall?: (Item.PreparedCall | null) | undefined;
            response?: (Item.Response | null) | undefined;
            runId: string;
            schemaVersion: string;
            startedAt: string;
            status: Item.Status;
            toolCalls: Item.ToolCalls.Item[];
            trace?: (Record<string, string | null> | null) | undefined;
        }

        export namespace Item {
            export interface Error_ {
                message: string;
                name?: (string | null) | undefined;
                stack?: (string | null) | undefined;
            }

            export const Operation = {
                Generate: "generate",
                Stream: "stream",
            } as const;
            export type Operation = (typeof Operation)[keyof typeof Operation];

            export interface PreparedCall {
                activeTools?: (string[] | null) | undefined;
                hash: string;
                providerOptionsHash?: (string | null) | undefined;
            }

            export interface Response {
                bodyHash?: (string | null) | undefined;
                finishReason?: (string | null) | undefined;
                /** Subset of headers preserved for the run drawer. */
                headers?: (Record<string, string | null> | null) | undefined;
                id?: (string | null) | undefined;
                modelId?: (string | null) | undefined;
                modelMetadata?: (Record<string, unknown> | null) | undefined;
                providerMetadata?: (Record<string, unknown> | null) | undefined;
                usage?: (Response.Usage | null) | undefined;
            }

            export namespace Response {
                export interface Usage {
                    cachedInputTokens?: (number | null) | undefined;
                    inputTokens?: (number | null) | undefined;
                    outputTokens?: (number | null) | undefined;
                    reasoningTokens?: (number | null) | undefined;
                    totalTokens?: (number | null) | undefined;
                }
            }

            export const Status = {
                Started: "started",
                Success: "success",
                Error: "error",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export type ToolCalls = ToolCalls.Item[];

            export namespace ToolCalls {
                export interface Item {
                    argsHash?: (string | null) | undefined;
                    /** Optional small preview of the tool args. */
                    argsPreview?: (Record<string, unknown> | null) | undefined;
                    callId: string;
                    durationMs?: (number | null) | undefined;
                    error?: (Item.Error_ | null) | undefined;
                    finishedAt?: (string | null) | undefined;
                    resultHash?: (string | null) | undefined;
                    resultPreview?: (Record<string, unknown> | null) | undefined;
                    startedAt: string;
                    status: Item.Status;
                    toolName: string;
                }

                export namespace Item {
                    export interface Error_ {
                        message: string;
                        name?: (string | null) | undefined;
                        stack?: (string | null) | undefined;
                    }

                    export const Status = {
                        Started: "started",
                        Success: "success",
                        Error: "error",
                    } as const;
                    export type Status = (typeof Status)[keyof typeof Status];
                }
            }
        }
    }
}
