// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface SearchAgentHashIndexRequest {
    q?: string;
    /** Comma-separated hash domains. */
    domains?: string;
}
