// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         session_id: "session_id",
 *         text: "text"
 *     }
 */
export interface SendAgentChatMessageRequest {
    name: string;
    session_id: string;
    text: string;
}
