// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface UpdateAgentRequest {
    name: string;
    description?: string | null;
    environment?: string | null;
    owner?: string | null;
    purpose?: string | null;
}
