// This file was auto-generated by Fern from our API Definition.

export interface AgentSnapshot {
    hashIndex: AgentSnapshot.HashIndex.Item[];
    runs: AgentSnapshot.Runs.Item[];
    summary: AgentSnapshot.Summary;
    versions: AgentSnapshot.Versions.Item[];
}

export namespace AgentSnapshot {
    export type HashIndex = HashIndex.Item[];

    export namespace HashIndex {
        export interface Item {
            /** Owning agent's display name — lets hash-index results deep-link straight to the agent detail surface. */
            agentName?: (string | null) | undefined;
            artifactId?: (string | null) | undefined;
            /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
            framework?: (Item.Framework | null) | undefined;
            hash: string;
            /** The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time). */
            kind: Item.Kind;
            observedAt: string;
            path: string;
            /** Stringified preview of the value rendered next to the hash. */
            preview?: (string | null) | undefined;
            runId?: (string | null) | undefined;
        }

        export namespace Item {
            /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
            export const Framework = {
                VercelAiSdk: "vercel-ai-sdk",
                OpenaiAgents: "openai-agents",
                Langchain: "langchain",
                Mastra: "mastra",
                LangchainPython: "langchain-python",
                Llamaindex: "llamaindex",
                Crewai: "crewai",
                Smolagents: "smolagents",
                PydanticAi: "pydantic-ai",
                Strands: "strands",
                GoogleAdk: "google-adk",
                OpenaiAgentsPython: "openai-agents-python",
                Autogen: "autogen",
                Eve: "eve",
                SalesforceAgentforce: "salesforce-agentforce",
            } as const;
            export type Framework = (typeof Framework)[keyof typeof Framework];
            /** The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time). */
            export const Kind = {
                AgentRoot: "agent.root",
                Prompt: "prompt",
                ModelContract: "model.contract",
                ProviderOptions: "provider.options",
                ToolContract: "tool.contract",
                RuntimePolicy: "runtime.policy",
                Dependency: "dependency",
                KnowledgeContract: "knowledge.contract",
                WorkflowGraph: "workflow.graph",
                EffectiveRun: "effective.run",
                ProviderObservation: "provider.observation",
                Operational: "operational",
                Output: "output",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export type Runs = Runs.Item[];

    export namespace Runs {
        export interface Item {
            artifactId: string;
            callOptionsHash?: (string | null) | undefined;
            configHash: string;
            durationMs?: (number | null) | undefined;
            error?: (Item.Error_ | null) | undefined;
            finishedAt?: (string | null) | undefined;
            inputHash?: (string | null) | undefined;
            operation: Item.Operation;
            preparedCall?: (Item.PreparedCall | null) | undefined;
            response?: (Item.Response | null) | undefined;
            runId: string;
            schemaVersion: string;
            startedAt: string;
            status: Item.Status;
            toolCalls: Item.ToolCalls.Item[];
            trace?: (Record<string, string | null> | null) | undefined;
        }

        export namespace Item {
            export interface Error_ {
                message: string;
                name?: (string | null) | undefined;
                stack?: (string | null) | undefined;
            }

            export const Operation = {
                Generate: "generate",
                Stream: "stream",
            } as const;
            export type Operation = (typeof Operation)[keyof typeof Operation];

            export interface PreparedCall {
                activeTools?: (string[] | null) | undefined;
                hash: string;
                providerOptionsHash?: (string | null) | undefined;
            }

            export interface Response {
                bodyHash?: (string | null) | undefined;
                finishReason?: (string | null) | undefined;
                /** Subset of headers preserved for the run drawer. */
                headers?: (Record<string, string | null> | null) | undefined;
                id?: (string | null) | undefined;
                modelId?: (string | null) | undefined;
                modelMetadata?: (Record<string, unknown> | null) | undefined;
                providerMetadata?: (Record<string, unknown> | null) | undefined;
                usage?: (Response.Usage | null) | undefined;
            }

            export namespace Response {
                export interface Usage {
                    cachedInputTokens?: (number | null) | undefined;
                    inputTokens?: (number | null) | undefined;
                    outputTokens?: (number | null) | undefined;
                    reasoningTokens?: (number | null) | undefined;
                    totalTokens?: (number | null) | undefined;
                }
            }

            export const Status = {
                Started: "started",
                Success: "success",
                Error: "error",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export type ToolCalls = ToolCalls.Item[];

            export namespace ToolCalls {
                export interface Item {
                    argsHash?: (string | null) | undefined;
                    /** Optional small preview of the tool args. */
                    argsPreview?: (Record<string, unknown> | null) | undefined;
                    callId: string;
                    durationMs?: (number | null) | undefined;
                    error?: (Item.Error_ | null) | undefined;
                    finishedAt?: (string | null) | undefined;
                    resultHash?: (string | null) | undefined;
                    resultPreview?: (Record<string, unknown> | null) | undefined;
                    startedAt: string;
                    status: Item.Status;
                    toolName: string;
                }

                export namespace Item {
                    export interface Error_ {
                        message: string;
                        name?: (string | null) | undefined;
                        stack?: (string | null) | undefined;
                    }

                    export const Status = {
                        Started: "started",
                        Success: "success",
                        Error: "error",
                    } as const;
                    export type Status = (typeof Status)[keyof typeof Status];
                }
            }
        }
    }

    export interface Summary {
        capabilityTags?: (string[] | null) | undefined;
        category?: (string | null) | undefined;
        description?: (string | null) | undefined;
        environment?: (string | null) | undefined;
        /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
        framework: Summary.Framework;
        /** Last drift event, if any. */
        lastDriftAt?: (string | null) | undefined;
        lastRunAt?: (string | null) | undefined;
        latestVersion: string;
        model: Summary.Model;
        modelLabel: string;
        name: string;
        owner?: (string | null) | undefined;
        personaSummary?: (string | null) | undefined;
        playgroundUrl?: (string | null) | undefined;
        purpose?: (string | null) | undefined;
        runbookUrl?: (string | null) | undefined;
        successRate: number;
        totalRuns: number;
        versionCount: number;
    }

    export namespace Summary {
        /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
        export const Framework = {
            VercelAiSdk: "vercel-ai-sdk",
            OpenaiAgents: "openai-agents",
            Langchain: "langchain",
            Mastra: "mastra",
            LangchainPython: "langchain-python",
            Llamaindex: "llamaindex",
            Crewai: "crewai",
            Smolagents: "smolagents",
            PydanticAi: "pydantic-ai",
            Strands: "strands",
            GoogleAdk: "google-adk",
            OpenaiAgentsPython: "openai-agents-python",
            Autogen: "autogen",
            Eve: "eve",
            SalesforceAgentforce: "salesforce-agentforce",
        } as const;
        export type Framework = (typeof Framework)[keyof typeof Framework];

        export interface Model {
            label: string;
            modelId?: (string | null) | undefined;
            provider?: (string | null) | undefined;
        }
    }

    export type Versions = Versions.Item[];

    export namespace Versions {
        export interface Item {
            artifact: Item.Artifact;
            lastRunAt?: (string | null) | undefined;
            meanDurationMs?: (number | null) | undefined;
            p95DurationMs?: (number | null) | undefined;
            resolvedModelIds: string[];
            runCount: number;
            status: Item.Status;
            /** Successful runs / total runs (0..1). */
            successRate: number;
            totalTokens?: (number | null) | undefined;
        }

        export namespace Item {
            export interface Artifact {
                artifactId: string;
                configHash: string;
                description?: (string | null) | undefined;
                /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
                framework: Artifact.Framework;
                /** Compact preview of the input contract this artifact expects. */
                inputContractPreview?: (Artifact.InputContractPreview | null) | undefined;
                instructions?: (string | null) | undefined;
                instructionsHash?: (string | null) | undefined;
                knowledgeSources?: (Artifact.KnowledgeSources.Item[] | null) | undefined;
                metadata?: (Record<string, unknown> | null) | undefined;
                model: Artifact.Model;
                name: string;
                /** Compact preview of the output contract this artifact emits. */
                outputContractPreview?: (Artifact.OutputContractPreview | null) | undefined;
                policy?: (Artifact.Policy | null) | undefined;
                provenance: Artifact.Provenance;
                providerOptions?: (Record<string, unknown> | null) | undefined;
                providerOptionsHash?: (string | null) | undefined;
                /** Schema marker — frontend code matches against the literal string `"agent-artifact-v1"` so newer payloads can co-exist when we evolve the shape. */
                schemaVersion: string;
                tools: Artifact.Tools.Item[];
                version: string;
                workflowGraphPreview?: (Artifact.WorkflowGraphPreview | null) | undefined;
            }

            export namespace Artifact {
                /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
                export const Framework = {
                    VercelAiSdk: "vercel-ai-sdk",
                    OpenaiAgents: "openai-agents",
                    Langchain: "langchain",
                    Mastra: "mastra",
                    LangchainPython: "langchain-python",
                    Llamaindex: "llamaindex",
                    Crewai: "crewai",
                    Smolagents: "smolagents",
                    PydanticAi: "pydantic-ai",
                    Strands: "strands",
                    GoogleAdk: "google-adk",
                    OpenaiAgentsPython: "openai-agents-python",
                    Autogen: "autogen",
                    Eve: "eve",
                    SalesforceAgentforce: "salesforce-agentforce",
                } as const;
                export type Framework = (typeof Framework)[keyof typeof Framework];

                /**
                 * Compact preview of the input contract this artifact expects.
                 */
                export interface InputContractPreview {
                    /** Representative example payload. */
                    example?: unknown | undefined;
                    /** One-line shape summary. */
                    schemaSummary?: (string | null) | undefined;
                }

                export type KnowledgeSources = KnowledgeSources.Item[];

                export namespace KnowledgeSources {
                    export interface Item {
                        /** Optional jump-out link. */
                        href?: (string | null) | undefined;
                        id: string;
                        kind: Item.Kind;
                        label: string;
                        /** Optional human-readable size hint, e.g. "12.4k docs". */
                        sizeLabel?: (string | null) | undefined;
                    }

                    export namespace Item {
                        export const Kind = {
                            Vector: "vector",
                            Doc: "doc",
                            Table: "table",
                            Graph: "graph",
                        } as const;
                        export type Kind = (typeof Kind)[keyof typeof Kind];
                    }
                }

                export interface Model {
                    label: string;
                    modelId?: (string | null) | undefined;
                    provider?: (string | null) | undefined;
                }

                /**
                 * Compact preview of the output contract this artifact emits.
                 */
                export interface OutputContractPreview {
                    /** Representative example payload. */
                    example?: unknown | undefined;
                    /** One-line shape summary. */
                    schemaSummary?: (string | null) | undefined;
                }

                export interface Policy {
                    allowedTools?: (string[] | null) | undefined;
                    approvalRequired?: (string[] | null) | undefined;
                    maxSteps?: (number | null) | undefined;
                    metadata?: (Record<string, unknown> | null) | undefined;
                }

                export interface Provenance {
                    aiSdkVersion?: (string | null) | undefined;
                    createdAt: string;
                    dependencyLockHash?: (string | null) | undefined;
                    frameworkVersion?: (string | null) | undefined;
                    gitSha?: (string | null) | undefined;
                    publishedBy?: (string | null) | undefined;
                }

                export type Tools = Tools.Item[];

                export namespace Tools {
                    export interface Item {
                        description?: (string | null) | undefined;
                        inputSchemaHash?: (string | null) | undefined;
                        /** Optional small input-schema preview rendered in the Tools tab. */
                        inputSchemaPreview?: (Record<string, unknown> | null) | undefined;
                        metadata?: (Record<string, unknown> | null) | undefined;
                        name: string;
                    }
                }

                export interface WorkflowGraphPreview {
                    edges: WorkflowGraphPreview.Edges.Item[];
                    nodes: WorkflowGraphPreview.Nodes.Item[];
                }

                export namespace WorkflowGraphPreview {
                    export type Edges = Edges.Item[];

                    export namespace Edges {
                        export interface Item {
                            from: string;
                            /** Optional short label rendered along the edge. */
                            label?: (string | null) | undefined;
                            to: string;
                        }
                    }

                    export type Nodes = Nodes.Item[];

                    export namespace Nodes {
                        export interface Item {
                            id: string;
                            kind: Item.Kind;
                            label: string;
                            /** Optional tool name reference for tool nodes. */
                            toolName?: (string | null) | undefined;
                        }

                        export namespace Item {
                            export const Kind = {
                                Input: "input",
                                Tool: "tool",
                                Model: "model",
                                Branch: "branch",
                                Output: "output",
                            } as const;
                            export type Kind = (typeof Kind)[keyof typeof Kind];
                        }
                    }
                }
            }

            export const Status = {
                Current: "current",
                Stable: "stable",
                Deprecated: "deprecated",
                Draft: "draft",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
