// This file was auto-generated by Fern from our API Definition.

/**
 * A live chat conversation with a registered agent version. Sessions are in-memory (lost on restart); the events, trace, and recorded run are durable.
 */
export interface AgentChatSession {
    agentName: string;
    /** Resolved registry version the session executes (`current`, else `stable`), pinned at session creation. */
    agentVersion: string;
    artifactId: string;
    messages: AgentChatSession.Messages.Item[];
    /** Registry run id of the most recently recorded turn. Runs are immutable observations, so each turn records its own run; the shared `traceId` ties them into one conversation. */
    runId: string;
    sessionId: string;
    startedAt: string;
    /** Trace id shared by every event of the conversation. Opens in the timeline and `/v1/trace-tree/:trace_id`. */
    traceId: string;
}

export namespace AgentChatSession {
    export type Messages = Messages.Item[];

    export namespace Messages {
        export interface Item {
            /** Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply. */
            error?: (string | null) | undefined;
            /** Canonical event ids this message ingested into the event store. */
            eventIds?: string[] | undefined;
            messageId: string;
            occurredAt: string;
            role: Item.Role;
            /** Tool calls made while producing this message. Empty for user messages and failed turns. */
            steps?: Item.Steps.Item[] | undefined;
            text: string;
        }

        export namespace Item {
            export const Role = {
                User: "user",
                Agent: "agent",
            } as const;
            export type Role = (typeof Role)[keyof typeof Role];
            export type Steps = Steps.Item[];

            export namespace Steps {
                /**
                 * One tool invocation the agent made while producing a chat turn. Mirrors what the executor reports from the agent's step telemetry; each step is also ingested as timeline events under the session trace (an `agent`/`tool.call` event plus a `source`/`eventType` result event).
                 */
                export interface Item {
                    argsPreview?: (Record<string, unknown> | null) | undefined;
                    /** Timeline event type of the tool result (e.g. `hotel-offers.search`). */
                    eventType: string;
                    resultPreview?: (Record<string, unknown> | null) | undefined;
                    /** Timeline source the tool call resolved against (e.g. `giata-sim`). */
                    source: string;
                    stepId: string;
                    /** Human-readable one-liner for the transcript and the timeline row. */
                    text: string;
                    toolName: string;
                }
            }
        }
    }
}
