// This file was auto-generated by Fern from our API Definition.

export interface AgentVersionSummary {
    artifact: AgentVersionSummary.Artifact;
    lastRunAt?: (string | null) | undefined;
    meanDurationMs?: (number | null) | undefined;
    p95DurationMs?: (number | null) | undefined;
    resolvedModelIds: string[];
    runCount: number;
    status: AgentVersionSummary.Status;
    /** Successful runs / total runs (0..1). */
    successRate: number;
    totalTokens?: (number | null) | undefined;
}

export namespace AgentVersionSummary {
    export interface Artifact {
        artifactId: string;
        configHash: string;
        description?: (string | null) | undefined;
        /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
        framework: Artifact.Framework;
        /** Compact preview of the input contract this artifact expects. */
        inputContractPreview?: (Artifact.InputContractPreview | null) | undefined;
        instructions?: (string | null) | undefined;
        instructionsHash?: (string | null) | undefined;
        knowledgeSources?: (Artifact.KnowledgeSources.Item[] | null) | undefined;
        metadata?: (Record<string, unknown> | null) | undefined;
        model: Artifact.Model;
        name: string;
        /** Compact preview of the output contract this artifact emits. */
        outputContractPreview?: (Artifact.OutputContractPreview | null) | undefined;
        policy?: (Artifact.Policy | null) | undefined;
        provenance: Artifact.Provenance;
        providerOptions?: (Record<string, unknown> | null) | undefined;
        providerOptionsHash?: (string | null) | undefined;
        /** Schema marker — frontend code matches against the literal string `"agent-artifact-v1"` so newer payloads can co-exist when we evolve the shape. */
        schemaVersion: string;
        tools: Artifact.Tools.Item[];
        version: string;
        workflowGraphPreview?: (Artifact.WorkflowGraphPreview | null) | undefined;
    }

    export namespace Artifact {
        /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
        export const Framework = {
            VercelAiSdk: "vercel-ai-sdk",
            OpenaiAgents: "openai-agents",
            Langchain: "langchain",
            Mastra: "mastra",
            LangchainPython: "langchain-python",
            Llamaindex: "llamaindex",
            Crewai: "crewai",
            Smolagents: "smolagents",
            PydanticAi: "pydantic-ai",
            Strands: "strands",
            GoogleAdk: "google-adk",
            OpenaiAgentsPython: "openai-agents-python",
            Autogen: "autogen",
            Eve: "eve",
            SalesforceAgentforce: "salesforce-agentforce",
        } as const;
        export type Framework = (typeof Framework)[keyof typeof Framework];

        /**
         * Compact preview of the input contract this artifact expects.
         */
        export interface InputContractPreview {
            /** Representative example payload. */
            example?: unknown | undefined;
            /** One-line shape summary. */
            schemaSummary?: (string | null) | undefined;
        }

        export type KnowledgeSources = KnowledgeSources.Item[];

        export namespace KnowledgeSources {
            export interface Item {
                /** Optional jump-out link. */
                href?: (string | null) | undefined;
                id: string;
                kind: Item.Kind;
                label: string;
                /** Optional human-readable size hint, e.g. "12.4k docs". */
                sizeLabel?: (string | null) | undefined;
            }

            export namespace Item {
                export const Kind = {
                    Vector: "vector",
                    Doc: "doc",
                    Table: "table",
                    Graph: "graph",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
            }
        }

        export interface Model {
            label: string;
            modelId?: (string | null) | undefined;
            provider?: (string | null) | undefined;
        }

        /**
         * Compact preview of the output contract this artifact emits.
         */
        export interface OutputContractPreview {
            /** Representative example payload. */
            example?: unknown | undefined;
            /** One-line shape summary. */
            schemaSummary?: (string | null) | undefined;
        }

        export interface Policy {
            allowedTools?: (string[] | null) | undefined;
            approvalRequired?: (string[] | null) | undefined;
            maxSteps?: (number | null) | undefined;
            metadata?: (Record<string, unknown> | null) | undefined;
        }

        export interface Provenance {
            aiSdkVersion?: (string | null) | undefined;
            createdAt: string;
            dependencyLockHash?: (string | null) | undefined;
            frameworkVersion?: (string | null) | undefined;
            gitSha?: (string | null) | undefined;
            publishedBy?: (string | null) | undefined;
        }

        export type Tools = Tools.Item[];

        export namespace Tools {
            export interface Item {
                description?: (string | null) | undefined;
                inputSchemaHash?: (string | null) | undefined;
                /** Optional small input-schema preview rendered in the Tools tab. */
                inputSchemaPreview?: (Record<string, unknown> | null) | undefined;
                metadata?: (Record<string, unknown> | null) | undefined;
                name: string;
            }
        }

        export interface WorkflowGraphPreview {
            edges: WorkflowGraphPreview.Edges.Item[];
            nodes: WorkflowGraphPreview.Nodes.Item[];
        }

        export namespace WorkflowGraphPreview {
            export type Edges = Edges.Item[];

            export namespace Edges {
                export interface Item {
                    from: string;
                    /** Optional short label rendered along the edge. */
                    label?: (string | null) | undefined;
                    to: string;
                }
            }

            export type Nodes = Nodes.Item[];

            export namespace Nodes {
                export interface Item {
                    id: string;
                    kind: Item.Kind;
                    label: string;
                    /** Optional tool name reference for tool nodes. */
                    toolName?: (string | null) | undefined;
                }

                export namespace Item {
                    export const Kind = {
                        Input: "input",
                        Tool: "tool",
                        Model: "model",
                        Branch: "branch",
                        Output: "output",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export const Status = {
        Current: "current",
        Stable: "stable",
        Deprecated: "deprecated",
        Draft: "draft",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
