// This file was auto-generated by Fern from our API Definition.

/**
 * Returned by `GET /api/platform/backtests/jobs/:id/trials/:trialId`. Everything the trial detail view renders in one round trip.
 */
export interface BacktestTrialDetailResponse {
    artifacts: BacktestTrialDetailResponse.Artifacts.Item[];
    /** Reward name → score for this trial. */
    rewards: Record<string, number>;
    /** Scorers bound to this trial's task (frozen verifiers first, then recipe-level graders), in binding order. */
    scorers: BacktestTrialDetailResponse.Scorers.Item[];
    /** Timeline steps ordered by ordinal. */
    steps: BacktestTrialDetailResponse.Steps.Item[];
    /** Row projection of `"BacktestTrial"`. */
    trial: BacktestTrialDetailResponse.Trial;
}

export namespace BacktestTrialDetailResponse {
    export type Artifacts = Artifacts.Item[];

    export namespace Artifacts {
        export interface Item {
            contentType?: (string | null) | undefined;
            createdAt: string;
            id: string;
            /** Row projection of `"BacktestArtifact"`. */
            kind: Item.Kind;
            path: string;
            sizeBytes?: (number | null) | undefined;
            trialId: string;
        }

        export namespace Item {
            /** Row projection of `"BacktestArtifact"`. */
            export const Kind = {
                AgentLog: "agent-log",
                VerifierLog: "verifier-log",
                Trajectory: "trajectory",
                Screenshot: "screenshot",
                RewardJson: "reward-json",
                RewardTxt: "reward-txt",
                Tar: "tar",
                Other: "other",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }

    export type Scorers = Scorers.Item[];

    export namespace Scorers {
        /**
         * A scorer as the trial view needs it: the frozen grader snapshot the reward key points at, plus the reward key itself so the UI can join scores to names without reconstructing `grader_<id>`.
         *
         * Resolved from the job's pinned Dataset Version items (task verifiers, `source: dataset`) and the recipe's own grader list.
         */
        export interface Item {
            grader: Item.Grader;
            /** Reward key this scorer's score is stored under (`grader_<id>`). */
            rewardKey: string;
        }

        export namespace Item {
            export interface Grader {
                /** Code handler snapshot — required when `kind` is `code`. */
                code?: (Grader.Code | null) | undefined;
                /** Optional human-readable explanation of why this grader was proposed. For rubric graders this doubles as the judge prompt; library scorers inline their prompt here at launch so the recipe stays self-describing. */
                evidence?: (string | null) | undefined;
                id: string;
                /** LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior. */
                judge?: (Grader.Judge | null) | undefined;
                kind: Grader.Kind;
                label: string;
                /** Scores at or above this value render as passing in results. */
                passThreshold?: (number | null) | undefined;
                /** Provenance: the library `Scorer.id` this grader was created from (when `source` is `library`). The prompt is snapshotted into `evidence` at launch, so editing the scorer later never mutates a past run. */
                scorerId?: (string | null) | undefined;
                /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                source: Grader.Source;
                /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                weight: Grader.Weight;
            }

            export namespace Grader {
                /**
                 * Code handler snapshot — required when `kind` is `code`.
                 */
                export interface Code {
                    /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                    language: Code.Language;
                    source: string;
                }

                export namespace Code {
                    /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                    export const Language = {
                        Python: "python",
                        Typescript: "typescript",
                    } as const;
                    export type Language = (typeof Language)[keyof typeof Language];
                }

                /**
                 * LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior.
                 */
                export interface Judge {
                    /** Allow the judge to decline non-applicable cases; skipped cases emit no reward key instead of scoring 0. */
                    allowSkip?: boolean | undefined;
                    /** Choice→score mapping. Non-empty forces the judge to pick one choice; the mapped score is the result. */
                    choiceScores?: Judge.ChoiceScores.Item[] | undefined;
                    /** Judge model override; `None` uses the server default. */
                    model?: (string | null) | undefined;
                    /** Ask the judge to reason step-by-step before answering. */
                    useCot?: boolean | undefined;
                }

                export namespace Judge {
                    export type ChoiceScores = ChoiceScores.Item[];

                    export namespace ChoiceScores {
                        /**
                         * One judge choice mapped to a numeric score, e.g. `A → 1.0`, `B → 0.5`, `C → 0.0`. When a judge scorer declares choices, the model must pick exactly one and the mapped score is the result.
                         */
                        export interface Item {
                            label: string;
                            score: number;
                        }
                    }
                }

                export const Kind = {
                    Rubric: "rubric",
                    Classifier: "classifier",
                    Metric: "metric",
                    Embedding: "embedding",
                    Assertion: "assertion",
                    Code: "code",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
                /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                export const Source = {
                    Proposed: "proposed",
                    Library: "library",
                    Custom: "custom",
                    Dataset: "dataset",
                } as const;
                export type Source = (typeof Source)[keyof typeof Source];
                /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                export const Weight = {
                    Low: "low",
                    Med: "med",
                    High: "high",
                } as const;
                export type Weight = (typeof Weight)[keyof typeof Weight];
            }
        }
    }

    export type Steps = Steps.Item[];

    export namespace Steps {
        /**
         * Row projection of `"BacktestTrialStep"`.
         */
        export interface Item {
            /** Who performed a step; one timeline lane per actor. */
            actor: Item.Actor;
            createdAt: string;
            /** `None` for instantaneous steps (seed events, state changes). */
            endedAt?: (string | null) | undefined;
            /** Frozen verifier id (or recipe grader id) for `grade` steps. */
            graderId?: (string | null) | undefined;
            id: string;
            /** What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked. */
            kind: Item.Kind;
            /** Position within the trial; steps are returned ordered by it. */
            ordinal: number;
            /** Free-form detail: `request`/`response` for tool calls, `text` for messages, `reasoning` for judge grades, and so on. */
            payload?: unknown | undefined;
            /** Grader score in `[0, 1]` for `grade` steps. */
            score?: (number | null) | undefined;
            startedAt: string;
            /** Outcome colouring for a step. `None` renders neutral. */
            status?: (Item.Status | null) | undefined;
            title: string;
            trialId: string;
        }

        export namespace Item {
            /** Who performed a step; one timeline lane per actor. */
            export const Actor = {
                Environment: "environment",
                Agent: "agent",
                Verifier: "verifier",
                Grader: "grader",
            } as const;
            export type Actor = (typeof Actor)[keyof typeof Actor];
            /** What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked. */
            export const Kind = {
                SeedEvent: "seed-event",
                StateChange: "state-change",
                ToolCall: "tool-call",
                Message: "message",
                FinalAnswer: "final-answer",
                Phase: "phase",
                VerifierRun: "verifier-run",
                Grade: "grade",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
            /** Outcome colouring for a step. `None` renders neutral. */
            export const Status = {
                Ok: "ok",
                Warn: "warn",
                Error: "error",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }

    /**
     * Row projection of `"BacktestTrial"`.
     */
    export interface Trial {
        agentId: string;
        agentLabel: string;
        attempt: number;
        caseCluster?: (string | null) | undefined;
        caseId: string;
        createdAt: string;
        durationMs?: (number | null) | undefined;
        /** Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans. */
        exception?: (Trial.Exception | null) | undefined;
        id: string;
        /** The case instruction this trial executed — persisted at launch so result surfaces can show the real prompt instead of reconstructing (or inventing) one client-side. */
        instruction?: (string | null) | undefined;
        isBaseline: boolean;
        jobId: string;
        sandboxId?: (string | null) | undefined;
        /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
        status: Trial.Status;
        tenantId: string;
        /** Per-phase timing bookkeeping. Each pair is `(started_at, finished_at)`; `None` until that phase starts/ends. */
        timings: Trial.Timings;
        updatedAt: string;
    }

    export namespace Trial {
        /**
         * Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans.
         */
        export interface Exception {
            kind: string;
            message: string;
        }

        /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
        export const Status = {
            Pending: "pending",
            Setup: "setup",
            Running: "running",
            Verifying: "verifying",
            Succeeded: "succeeded",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];

        /**
         * Per-phase timing bookkeeping. Each pair is `(started_at, finished_at)`; `None` until that phase starts/ends.
         */
        export interface Timings {
            agentRunFinishedAt?: (string | null) | undefined;
            agentRunStartedAt?: (string | null) | undefined;
            agentSetupFinishedAt?: (string | null) | undefined;
            agentSetupStartedAt?: (string | null) | undefined;
            envSetupFinishedAt?: (string | null) | undefined;
            envSetupStartedAt?: (string | null) | undefined;
            verifierFinishedAt?: (string | null) | undefined;
            verifierStartedAt?: (string | null) | undefined;
        }
    }
}
