// This file was auto-generated by Fern from our API Definition.

export interface BacktestJobDetailResponse {
    /** Row projection of `"BacktestJob"`. */
    job: BacktestJobDetailResponse.Job;
    /** Compact projection of a backtest run rendered on the list view. Combines the recipe identity (mode, environment, agents, dataset) with run lifecycle metadata (status, verdict, divergences). */
    run: BacktestJobDetailResponse.Run;
}

export namespace BacktestJobDetailResponse {
    /**
     * Row projection of `"BacktestJob"`.
     */
    export interface Job {
        completedTrials: number;
        createdAt: string;
        createdBy?: (string | null) | undefined;
        /** Mutable Dataset selected when the job was launched. */
        datasetId?: (string | null) | undefined;
        /** Immutable Dataset Version used to compile this job's cases. Once set, later working-copy edits cannot alter the run inputs. */
        datasetVersionId?: (string | null) | undefined;
        exceptionKind?: (string | null) | undefined;
        failedTrials: number;
        finishedAt?: (string | null) | undefined;
        id: string;
        mode: Job.Mode;
        nConcurrent: number;
        name: string;
        recipe?: unknown | undefined;
        /** Retry policy applied to transient trial failures (network errors, sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass `null` on the wire (`None` here) to fall back to defaults. */
        retryConfig?: (Job.RetryConfig | null) | undefined;
        /** Sandbox driver selected by trusted server policy at submit time. Echoed onto the `BacktestJob.sandboxDriver` column so persisted jobs record which implementation backed the `Sandbox` trait. */
        sandboxDriver: Job.SandboxDriver;
        scheduledFor?: (string | null) | undefined;
        startedAt?: (string | null) | undefined;
        /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
        status: Job.Status;
        tenantId: string;
        totalTrials?: (number | null) | undefined;
        updatedAt: string;
        verdict?: (string | null) | undefined;
    }

    export namespace Job {
        export const Mode = {
            Replay: "replay",
            Compare: "compare",
            Regression: "regression",
            Suite: "suite",
        } as const;
        export type Mode = (typeof Mode)[keyof typeof Mode];

        /**
         * Retry policy applied to transient trial failures (network errors, sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass `null` on the wire (`None` here) to fall back to defaults.
         */
        export interface RetryConfig {
            /** Exception kinds that explicitly should not be retried even if otherwise matched by `include_exceptions`. */
            excludeExceptions?: (string[] | null) | undefined;
            /** When set, only exception kinds in this list trigger a retry. `None` means "retry every transient kind". */
            includeExceptions?: (string[] | null) | undefined;
            maxRetries: number;
            maxWaitSec: number;
            minWaitSec: number;
            waitMultiplier: number;
        }

        /** Sandbox driver selected by trusted server policy at submit time. Echoed onto the `BacktestJob.sandboxDriver` column so persisted jobs record which implementation backed the `Sandbox` trait. */
        export const SandboxDriver = {
            Docker: "docker",
            Daytona: "daytona",
            Mock: "mock",
        } as const;
        export type SandboxDriver = (typeof SandboxDriver)[keyof typeof SandboxDriver];
        /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
        export const Status = {
            Pending: "pending",
            Running: "running",
            Succeeded: "succeeded",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }

    /**
     * Compact projection of a backtest run rendered on the list view. Combines the recipe identity (mode, environment, agents, dataset) with run lifecycle metadata (status, verdict, divergences).
     */
    export interface Run {
        /** Agent ids participating in the run; the first is the baseline. */
        agentIds: string[];
        /** Display label for the dataset / production window seed. */
        datasetLabel: string;
        /** Divergences observed (only set when status is `done` / `failed`). */
        divergences?: (number | null) | undefined;
        environmentLabel?: (string | null) | undefined;
        hue?: (string | null) | undefined;
        id: string;
        mode: Run.Mode;
        /** Display name of the run (matches `BacktestRecipe.name`). */
        name: string;
        owner?: (string | null) | undefined;
        scheduledFor?: (string | null) | undefined;
        status: Run.Status;
        /** Total cases × agents; null while still drafting. */
        totalRuns?: (number | null) | undefined;
        /** ISO timestamp of the most recent state change — drives "ago". */
        updatedAt: string;
        verdict?: (string | null) | undefined;
    }

    export namespace Run {
        export const Mode = {
            Replay: "replay",
            Compare: "compare",
            Regression: "regression",
            Suite: "suite",
        } as const;
        export type Mode = (typeof Mode)[keyof typeof Mode];
        export const Status = {
            Running: "running",
            Done: "done",
            Paused: "paused",
            Scheduled: "scheduled",
            Draft: "draft",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
