// This file was auto-generated by Fern from our API Definition.

export interface CancelBacktestJobResponse {
    /** True only when an active execution accepted cancellation. */
    aborted: boolean;
    jobId: string;
    /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
    previousStatus: CancelBacktestJobResponse.PreviousStatus;
}

export namespace CancelBacktestJobResponse {
    /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
    export const PreviousStatus = {
        Pending: "pending",
        Running: "running",
        Succeeded: "succeeded",
        Failed: "failed",
        Cancelled: "cancelled",
    } as const;
    export type PreviousStatus = (typeof PreviousStatus)[keyof typeof PreviousStatus];
}
