// This file was auto-generated by Fern from our API Definition.

export interface CompileEnvironmentResponse {
    environmentId: string;
    environmentSlug: string;
    versionId: string;
    version: string;
    tenantId: string;
    datasetSnapshotId: string;
    scenarioId: string;
    bundleId: string;
    sha256: string;
    uri: string;
    packageUri: string;
    rootDir: string;
    sizeBytes: number;
    warnings: string[];
    files: string[];
    manifest: Record<string, unknown>;
}
