// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

export interface CreatedSdkKey extends ChronicleLabsApi.SdkKey {
    /** One-time plaintext SDK bearer token. */
    bearer: string;
}
