// This file was auto-generated by Fern from our API Definition.

export interface CreateBacktestJobResponse {
    jobId: string;
    /** Compact projection of a backtest run rendered on the list view. Combines the recipe identity (mode, environment, agents, dataset) with run lifecycle metadata (status, verdict, divergences). */
    run: CreateBacktestJobResponse.Run;
}

export namespace CreateBacktestJobResponse {
    /**
     * Compact projection of a backtest run rendered on the list view. Combines the recipe identity (mode, environment, agents, dataset) with run lifecycle metadata (status, verdict, divergences).
     */
    export interface Run {
        /** Agent ids participating in the run; the first is the baseline. */
        agentIds: string[];
        /** Display label for the dataset / production window seed. */
        datasetLabel: string;
        /** Divergences observed (only set when status is `done` / `failed`). */
        divergences?: (number | null) | undefined;
        environmentLabel?: (string | null) | undefined;
        hue?: (string | null) | undefined;
        id: string;
        mode: Run.Mode;
        /** Display name of the run (matches `BacktestRecipe.name`). */
        name: string;
        owner?: (string | null) | undefined;
        scheduledFor?: (string | null) | undefined;
        status: Run.Status;
        /** Total cases × agents; null while still drafting. */
        totalRuns?: (number | null) | undefined;
        /** ISO timestamp of the most recent state change — drives "ago". */
        updatedAt: string;
        verdict?: (string | null) | undefined;
    }

    export namespace Run {
        export const Mode = {
            Replay: "replay",
            Compare: "compare",
            Regression: "regression",
            Suite: "suite",
        } as const;
        export type Mode = (typeof Mode)[keyof typeof Mode];
        export const Status = {
            Running: "running",
            Done: "done",
            Paused: "paused",
            Scheduled: "scheduled",
            Draft: "draft",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
