// This file was auto-generated by Fern from our API Definition.

export interface DatasetSavedView {
    createdBy?: (string | null) | undefined;
    description?: (string | null) | undefined;
    id: string;
    name: string;
    scope: DatasetSavedView.Scope;
    shortcut?: (string | null) | undefined;
    state: DatasetSavedView.State;
    updatedAt?: (string | null) | undefined;
}

export namespace DatasetSavedView {
    export const Scope = {
        Personal: "personal",
        Workspace: "workspace",
    } as const;
    export type Scope = (typeof Scope)[keyof typeof Scope];

    export interface State {
        density?: (string | null) | undefined;
        displayProperties?: (string[] | null) | undefined;
        filters?: (State.Filters.Item[] | null) | undefined;
        groupBy?: (string | null) | undefined;
        lens?: (string | null) | undefined;
        /** Deprecated since the table moved to TanStack multi-column sort. New views write `sorting`; this stays as a back-compat fallback for views captured before the migration. */
        ordering?: (string | null) | undefined;
        search?: (string | null) | undefined;
        showEmptyGroups?: (boolean | null) | undefined;
        sorting?: (State.Sorting.Item[] | null) | undefined;
    }

    export namespace State {
        export type Filters = Filters.Item[];

        export namespace Filters {
            export interface Item {
                columnId: string;
                id?: (string | null) | undefined;
                operator: string;
                value?: unknown | undefined;
            }
        }

        export type Sorting = Sorting.Item[];

        export namespace Sorting {
            export interface Item {
                desc: boolean;
                id: string;
            }
        }
    }
}
