// This file was auto-generated by Fern from our API Definition.

export interface DatasetCluster {
    /** CSS color for the cluster (e.g. `"var(--c-event-teal)"`). */
    color: string;
    description?: (string | null) | undefined;
    id: string;
    label: string;
    /** Optional pre-computed centroid hint in normalized [0..1] space. */
    similarityCenter?: (number[] | null) | undefined;
    traceIds: string[];
}
