// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

/**
 * A stable page ordered by event count and entity ID.
 */
export interface EntityListResponse {
    data: ChronicleLabsApi.EntityInfo[];
    /** Opaque position for the next request. */
    next_cursor?: (string | null) | undefined;
}
