// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

export interface EntityTypeListResponse {
    data: ChronicleLabsApi.EntityTypeInfo[];
    next_cursor?: (string | null) | undefined;
}
