// This file was auto-generated by Fern from our API Definition.

/**
 * A single entity and its event volume.
 */
export interface EntityInfo {
    entity_type: string;
    entity_id: string;
    event_count: number;
    first_seen?: (string | null) | undefined;
    last_seen?: (string | null) | undefined;
}
