// This file was auto-generated by Fern from our API Definition.

/**
 * An entity type in use and how much of it there is.
 */
export interface EntityTypeInfo {
    entity_type: string;
    entity_count: number;
    first_seen?: (string | null) | undefined;
    last_seen?: (string | null) | undefined;
}
