// This file was auto-generated by Fern from our API Definition.

export interface EnvironmentRecord {
    archivedAt?: (string | null) | undefined;
    createdAt: string;
    description?: (string | null) | undefined;
    id: string;
    label: string;
    slug: string;
    tenantId: string;
}
