// This file was auto-generated by Fern from our API Definition.

export interface EnvironmentSpec {
    datastores?: unknown[] | undefined;
    interception: EnvironmentSpec.Interception;
    mcp?: EnvironmentSpec.Mcp.Item[] | undefined;
    services?: EnvironmentSpec.Services.Item[] | undefined;
    /** Twins this environment wants running (`backend/twins` models), seeded from the environment's dataset when spun up. */
    twins?: EnvironmentSpec.Twins.Item[] | undefined;
}

export namespace EnvironmentSpec {
    export interface Interception {
        installCa?: boolean | undefined;
        regularProxyPort?: number | undefined;
        transparentProxyPort?: number | undefined;
    }

    export type Mcp = Mcp.Item[];

    export namespace Mcp {
        export interface Item {
            command?: (string | null) | undefined;
            name: string;
            transport?: string | undefined;
            url?: (string | null) | undefined;
        }
    }

    export type Services = Services.Item[];

    export namespace Services {
        export interface Item {
            authorities?: string[] | undefined;
            name: string;
            openapiUri?: (string | null) | undefined;
        }
    }

    export type Twins = Twins.Item[];

    export namespace Twins {
        /**
         * One declared twin: which model to run and which captured hosts feed its seed (empty means the model's default, e.g. `slack.com`).
         */
        export interface Item {
            authorities?: string[] | undefined;
            /** Image override; defaults to the platform's per-service template. */
            image?: (string | null) | undefined;
            /** Twin model name, e.g. `slack`. */
            service: string;
        }
    }
}
