// This file was auto-generated by Fern from our API Definition.

export const EnvironmentVersionStatus = {
    Draft: "draft",
    Published: "published",
    Archived: "archived",
} as const;
export type EnvironmentVersionStatus = (typeof EnvironmentVersionStatus)[keyof typeof EnvironmentVersionStatus];
