// This file was auto-generated by Fern from our API Definition.

/**
 * RFC 9457 problem details, served as `application/problem+json`. The `code` member is the stable machine-readable slug to branch on; `type` and `title` are stable per problem class, and `detail` varies per occurrence. The `error` and `message` members are retained for existing clients and carry the same values as `code` and `detail`. The request identifier appears both in the `x-request-id` response header, for code to read and log, and in the `request_id` member, so it survives being copied into a support thread.
 */
export interface ErrorResponse {
    /** URI identifying the problem class */
    type: string;
    /** Short summary of the problem class, stable across occurrences */
    title: string;
    /** HTTP status code, always equal to the response status */
    status: number;
    /** Explanation specific to this occurrence */
    detail: string;
    /** Stable machine-readable slug to branch on */
    code: ErrorResponse.Code;
    /** Retained for existing clients. Same value as `code`. */
    error: string;
    /** Retained for existing clients. Same value as `detail`. */
    message: string;
    /** Whether the same request may succeed when retried without modification */
    retryable: boolean;
    /** Same value as the `x-request-id` response header. Quote it when reporting a problem; it identifies the exact request in our logs. */
    request_id?: string | undefined;
    details?: (unknown | null) | undefined;
}

export namespace ErrorResponse {
    /** Stable machine-readable slug to branch on */
    export const Code = {
        NotFound: "not_found",
        BadRequest: "bad_request",
        Unauthorized: "unauthorized",
        ValidationError: "validation_error",
        UnsupportedMediaType: "unsupported_media_type",
        PayloadTooLarge: "payload_too_large",
        RateLimited: "rate_limited",
        StreamReplayLimitExceeded: "stream_replay_limit_exceeded",
        StreamUnavailable: "stream_unavailable",
        ServiceOverloaded: "service_overloaded",
        RequestTimeout: "request_timeout",
        StreamError: "stream_error",
        StoreError: "store_error",
        InternalError: "internal_error",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
