// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

/**
 * A stored event. Immutable once written.
 */
export interface Event {
    /** Time-ordered identifier, sorts in creation order. */
    event_id: string;
    /** Organisation the event belongs to. */
    org_id: string;
    source: string;
    topic: string;
    event_type: string;
    /** When the event happened at the source. */
    event_time: string;
    /** When Chronicle received it. */
    ingestion_time: string;
    /** Source-defined body. Free-form by design. */
    payload?: (Record<string, unknown> | null) | undefined;
    media?: ChronicleLabsApi.MediaAttachment | undefined;
    /** Entity references supplied with the event at ingest time. */
    entity_refs?: ChronicleLabsApi.PendingEntityRef[] | undefined;
    raw_body?: (string | null) | undefined;
}
