// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

/**
 * One page of events, newest first. `next_cursor` is present only when `has_more` is true.
 */
export interface EventPage {
    data: ChronicleLabsApi.EventResult[];
    /** Whether a further page exists */
    has_more: boolean;
    /** Opaque cursor to pass as `cursor` on the next request */
    next_cursor?: (string | null) | undefined;
}
