// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

/**
 * An event with its entity references and optional search distance.
 */
export interface EventResult {
    event: ChronicleLabsApi.Event;
    entity_refs?: ChronicleLabsApi.EntityRef[] | undefined;
    search_distance?: (number | null) | undefined;
}
