// This file was auto-generated by Fern from our API Definition.

export interface HashIndexEntry {
    /** Owning agent's display name — lets hash-index results deep-link straight to the agent detail surface. */
    agentName?: (string | null) | undefined;
    artifactId?: (string | null) | undefined;
    /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
    framework?: (HashIndexEntry.Framework | null) | undefined;
    hash: string;
    /** The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time). */
    kind: HashIndexEntry.Kind;
    observedAt: string;
    path: string;
    /** Stringified preview of the value rendered next to the hash. */
    preview?: (string | null) | undefined;
    runId?: (string | null) | undefined;
}

export namespace HashIndexEntry {
    /** Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.). */
    export const Framework = {
        VercelAiSdk: "vercel-ai-sdk",
        OpenaiAgents: "openai-agents",
        Langchain: "langchain",
        Mastra: "mastra",
        LangchainPython: "langchain-python",
        Llamaindex: "llamaindex",
        Crewai: "crewai",
        Smolagents: "smolagents",
        PydanticAi: "pydantic-ai",
        Strands: "strands",
        GoogleAdk: "google-adk",
        OpenaiAgentsPython: "openai-agents-python",
        Autogen: "autogen",
        Eve: "eve",
        SalesforceAgentforce: "salesforce-agentforce",
    } as const;
    export type Framework = (typeof Framework)[keyof typeof Framework];
    /** The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time). */
    export const Kind = {
        AgentRoot: "agent.root",
        Prompt: "prompt",
        ModelContract: "model.contract",
        ProviderOptions: "provider.options",
        ToolContract: "tool.contract",
        RuntimePolicy: "runtime.policy",
        Dependency: "dependency",
        KnowledgeContract: "knowledge.contract",
        WorkflowGraph: "workflow.graph",
        EffectiveRun: "effective.run",
        ProviderObservation: "provider.observation",
        Operational: "operational",
        Output: "output",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
