// This file was auto-generated by Fern from our API Definition.

export interface IngestRequest {
    source: string;
    topic: string;
    event_type: string;
    entities?: Record<string, string> | undefined;
    payload?: (unknown | null) | undefined;
    timestamp?: (string | null) | undefined;
}
