// This file was auto-generated by Fern from our API Definition.

/**
 * One stable, ascending page of persisted trial rows and only the rewards attached to those rows.
 */
export interface ListBacktestJobTrialsResponse {
    hasMore: boolean;
    nextOffset?: (number | null) | undefined;
    /** Outer key = trial id; inner key = reward name. */
    rewards: Record<string, Record<string, number>>;
    trials: ListBacktestJobTrialsResponse.Trials.Item[];
}

export namespace ListBacktestJobTrialsResponse {
    export type Trials = Trials.Item[];

    export namespace Trials {
        /**
         * Row projection of `"BacktestTrial"`.
         */
        export interface Item {
            agentId: string;
            agentLabel: string;
            attempt: number;
            caseCluster?: (string | null) | undefined;
            caseId: string;
            createdAt: string;
            durationMs?: (number | null) | undefined;
            /** Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans. */
            exception?: (Item.Exception | null) | undefined;
            id: string;
            /** The case instruction this trial executed — persisted at launch so result surfaces can show the real prompt instead of reconstructing (or inventing) one client-side. */
            instruction?: (string | null) | undefined;
            isBaseline: boolean;
            jobId: string;
            sandboxId?: (string | null) | undefined;
            /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
            status: Item.Status;
            tenantId: string;
            /** Per-phase timing bookkeeping. Each pair is `(started_at, finished_at)`; `None` until that phase starts/ends. */
            timings: Item.Timings;
            updatedAt: string;
        }

        export namespace Item {
            /**
             * Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans.
             */
            export interface Exception {
                kind: string;
                message: string;
            }

            /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
            export const Status = {
                Pending: "pending",
                Setup: "setup",
                Running: "running",
                Verifying: "verifying",
                Succeeded: "succeeded",
                Failed: "failed",
                Cancelled: "cancelled",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];

            /**
             * Per-phase timing bookkeeping. Each pair is `(started_at, finished_at)`; `None` until that phase starts/ends.
             */
            export interface Timings {
                agentRunFinishedAt?: (string | null) | undefined;
                agentRunStartedAt?: (string | null) | undefined;
                agentSetupFinishedAt?: (string | null) | undefined;
                agentSetupStartedAt?: (string | null) | undefined;
                envSetupFinishedAt?: (string | null) | undefined;
                envSetupStartedAt?: (string | null) | undefined;
                verifierFinishedAt?: (string | null) | undefined;
                verifierStartedAt?: (string | null) | undefined;
            }
        }
    }
}
