// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

export interface ListEnvironmentsResponse {
    environments: ListEnvironmentsResponse.Environments.Item[];
}

export namespace ListEnvironmentsResponse {
    export type Environments = Environments.Item[];

    export namespace Environments {
        export interface Item {
            environment: ChronicleLabsApi.EnvironmentRecord;
            versions: ChronicleLabsApi.EnvironmentVersionRecord[];
        }
    }
}
