// This file was auto-generated by Fern from our API Definition.

/**
 * Media attached to an event, stored inline or by reference.
 */
export interface MediaAttachment {
    media_type: string;
    /** Inline bytes for small media. Absent when stored externally. */
    inline_blob?: (string | null) | undefined;
    /** URI for externally stored media. Absent when inline. */
    external_ref?: (string | null) | undefined;
    size_bytes: number;
}
