// This file was auto-generated by Fern from our API Definition.

/**
 * An entity reference as supplied at ingest, before it is stored.
 */
export interface PendingEntityRef {
    entity_type: string;
    entity_id: string;
}
