// This file was auto-generated by Fern from our API Definition.

export interface SignalRequest {
    event_id: string;
    signal_name: string;
    timestamp?: (string | null) | undefined;
    properties?: (unknown | null) | undefined;
    attachment_id?: (string | null) | undefined;
    signal_type?: (string | null) | undefined;
    sentiment?: (string | null) | undefined;
}
