// This file was auto-generated by Fern from our API Definition.

/**
 * The inferred payload shape for one source and event type.
 */
export interface SourceSchema {
    org_id: string;
    source: string;
    event_type: string;
    /** Bumped when the inferred shape changes. */
    version: number;
    field_names: string[];
    field_types: string[];
    sample_event?: (Record<string, unknown> | null) | undefined;
}
