// This file was auto-generated by Fern from our API Definition.

/**
 * A connected source and what has been seen from it.
 */
export interface SourceInfo {
    source: string;
    event_types: string[];
    event_count: number;
    first_seen?: (string | null) | undefined;
    last_seen?: (string | null) | undefined;
}
