// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

export interface SourceListResponse {
    data: ChronicleLabsApi.SourceInfo[];
    next_cursor?: (string | null) | undefined;
}
