// This file was auto-generated by Fern from our API Definition.

export interface SpanRequest {
    trace_id: string;
    span_id: string;
    parent_span_id?: (string | null) | undefined;
    event_id?: (string | null) | undefined;
    name: string;
    kind?: (string | null) | undefined;
    status?: (string | null) | undefined;
    started_at?: (string | null) | undefined;
    ended_at?: (string | null) | undefined;
    duration_ms?: (number | null) | undefined;
    attributes?: (unknown | null) | undefined;
    links?: (unknown | null) | undefined;
}
