// This file was auto-generated by Fern from our API Definition.

export interface TaskSuiteVersion {
    createdAt: string;
    createdBy?: (string | null) | undefined;
    datasetId: string;
    datasetRevision: number;
    description?: (string | null) | undefined;
    eventCount: number;
    id: string;
    itemCount: number;
    label?: (string | null) | undefined;
    version: number;
}
