// This file was auto-generated by Fern from our API Definition.

export interface TaskSuiteSnapshot {
    clusters: TaskSuiteSnapshot.Clusters.Item[];
    dataset: TaskSuiteSnapshot.Dataset;
    edges: TaskSuiteSnapshot.Edges.Item[];
    /** Optional pre-built event index used by the Timeline tab. */
    events?: (TaskSuiteSnapshot.Events.Item[] | null) | undefined;
    /** Task definitions, one per trace. Absent on snapshots built by clients that only render the timeline. */
    tasks?: (TaskSuiteSnapshot.Tasks.Item[] | null) | undefined;
    traces: TaskSuiteSnapshot.Traces.Item[];
}

export namespace TaskSuiteSnapshot {
    export type Clusters = Clusters.Item[];

    export namespace Clusters {
        export interface Item {
            /** CSS color for the cluster (e.g. `"var(--c-event-teal)"`). */
            color: string;
            description?: (string | null) | undefined;
            id: string;
            label: string;
            /** Optional pre-computed centroid hint in normalized [0..1] space. */
            similarityCenter?: (number[] | null) | undefined;
            traceIds: string[];
        }
    }

    export interface Dataset {
        /** Soft-archive timestamp. Present only when `includeArchived=true` or an archived Dataset is read directly. */
        archivedAt?: (string | null) | undefined;
        /** Display name of the dataset owner / creator. */
        createdBy?: (string | null) | undefined;
        description?: (string | null) | undefined;
        /** Optional total event count across all traces. */
        eventCount?: (number | null) | undefined;
        id: string;
        name: string;
        /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
        purpose?: (Dataset.Purpose | null) | undefined;
        /** Free-form pinned tags. */
        tags?: (string[] | null) | undefined;
        /** Number of traces currently in the dataset. */
        traceCount: number;
        /** ISO timestamp of the most recent addition. */
        updatedAt?: (string | null) | undefined;
    }

    export namespace Dataset {
        /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
        export const Purpose = {
            Eval: "eval",
            Training: "training",
            Replay: "replay",
            Review: "review",
        } as const;
        export type Purpose = (typeof Purpose)[keyof typeof Purpose];
    }

    export type Edges = Edges.Item[];

    export namespace Edges {
        export interface Item {
            fromTraceId: string;
            toTraceId: string;
            /** Similarity weight in [0..1]. */
            weight: number;
        }
    }

    export type Events = Events.Item[];

    export namespace Events {
        /**
         * A single event rendered as a mark on the stream timeline. The full shape lives next to dataset shapes because `DatasetSnapshot.events` is the only consumer that ships over the wire today.
         */
        export interface Item {
            actor?: (string | null) | undefined;
            /** Optional explicit color override; falls back to the source color. */
            color?: (string | null) | undefined;
            /** Looser, app-defined grouping key (e.g. `conversation_id`). */
            correlationKey?: (string | null) | undefined;
            id: string;
            message?: (string | null) | undefined;
            /** ISO timestamp. */
            occurredAt: string;
            /** Direct causal predecessor. */
            parentEventId?: (string | null) | undefined;
            /** Raw payload — shown JSON-pretty in the detail panel. */
            payload?: unknown | undefined;
            /** Source/system the event came from (e.g. `intercom`, `stripe`). */
            source: string;
            /** Optional grouping (capture stream id) — currently informational. */
            stream?: (string | null) | undefined;
            /** Trace this event belongs to. */
            traceId?: (string | null) | undefined;
            /** Human-friendly label for the trace. */
            traceLabel?: (string | null) | undefined;
            /** Event type within the source (e.g. `conversation.created`). */
            type: string;
        }
    }

    export type Tasks = Tasks.Item[];

    export namespace Tasks {
        /**
         * One task as frozen in a snapshot: the definition plus its verifiers with scorer content embedded. `trace_id` matches the `TraceSummary` in the same snapshot.
         */
        export interface Item {
            membershipId: string;
            /** The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service. */
            subjectKind: Item.SubjectKind;
            /** What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`). */
            task: Item.Task;
            traceId: string;
            verifiers: Item.Verifiers.Item[];
        }

        export namespace Item {
            /** The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service. */
            export const SubjectKind = {
                Trace: "trace",
                Event: "event",
                Task: "task",
            } as const;
            export type SubjectKind = (typeof SubjectKind)[keyof typeof SubjectKind];

            /**
             * What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`).
             */
            export interface Task {
                /** Runtime knobs a task carries, mirroring the `[agent]`, `[verifier]` and `[environment]` tables of a Harbor `task.toml`. Every field is optional; the server policy fills defaults at launch. */
                config?: Task.Config | undefined;
                environmentId?: (string | null) | undefined;
                environmentVersionId?: (string | null) | undefined;
                /** What "done correctly" looks like. Passed to graders as the gold reference. For trace-seeded tasks this defaults to the events that followed the seed cutoff. */
                expectedOutcome?: unknown | undefined;
                /** The goal, as markdown. Harbor's `instruction.md`. */
                instruction?: (string | null) | undefined;
                /** Id of the last seed event. Events up to and including it are the context the agent sees; later events are the recorded outcome. */
                seedCutoffEventId?: (string | null) | undefined;
                /** Optional oracle: how a correct agent would solve this. Harbor's `solution/solve.sh` body. */
                solution?: (string | null) | undefined;
                /** Short human name. Defaults to the trace label for trace-seeded tasks. */
                title?: (string | null) | undefined;
            }

            export namespace Task {
                /**
                 * Runtime knobs a task carries, mirroring the `[agent]`, `[verifier]` and `[environment]` tables of a Harbor `task.toml`. Every field is optional; the server policy fills defaults at launch.
                 */
                export interface Config {
                    agentTimeoutSec?: (number | null) | undefined;
                    /** Network policy for the agent sandbox, mirroring Harbor's `[environment].network_mode`. */
                    networkMode?: (Config.NetworkMode | null) | undefined;
                    verifierTimeoutSec?: (number | null) | undefined;
                }

                export namespace Config {
                    /** Network policy for the agent sandbox, mirroring Harbor's `[environment].network_mode`. */
                    export const NetworkMode = {
                        Public: "public",
                        NoNetwork: "no-network",
                    } as const;
                    export type NetworkMode = (typeof NetworkMode)[keyof typeof NetworkMode];
                }
            }

            export type Verifiers = Verifiers.Item[];

            export namespace Verifiers {
                export interface Item {
                    /** Code handler snapshot — required when `kind` is `code`. */
                    code?: (Item.Code | null) | undefined;
                    /** Optional human-readable explanation of why this grader was proposed. For rubric graders this doubles as the judge prompt; library scorers inline their prompt here at launch so the recipe stays self-describing. */
                    evidence?: (string | null) | undefined;
                    id: string;
                    /** LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior. */
                    judge?: (Item.Judge | null) | undefined;
                    kind: Item.Kind;
                    label: string;
                    /** Scores at or above this value render as passing in results. */
                    passThreshold?: (number | null) | undefined;
                    /** Provenance: the library `Scorer.id` this grader was created from (when `source` is `library`). The prompt is snapshotted into `evidence` at launch, so editing the scorer later never mutates a past run. */
                    scorerId?: (string | null) | undefined;
                    /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                    source: Item.Source;
                    /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                    weight: Item.Weight;
                }

                export namespace Item {
                    /**
                     * Code handler snapshot — required when `kind` is `code`.
                     */
                    export interface Code {
                        /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                        language: Code.Language;
                        source: string;
                    }

                    export namespace Code {
                        /** Language of a code scorer. Handlers run inside the trial's trusted verifier sandbox: Python via `python3`, TypeScript via `node` (>= 22.6, type-stripping) — both shipped in the sandbox runtime image. */
                        export const Language = {
                            Python: "python",
                            Typescript: "typescript",
                        } as const;
                        export type Language = (typeof Language)[keyof typeof Language];
                    }

                    /**
                     * LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior.
                     */
                    export interface Judge {
                        /** Allow the judge to decline non-applicable cases; skipped cases emit no reward key instead of scoring 0. */
                        allowSkip?: boolean | undefined;
                        /** Choice→score mapping. Non-empty forces the judge to pick one choice; the mapped score is the result. */
                        choiceScores?: Judge.ChoiceScores.Item[] | undefined;
                        /** Judge model override; `None` uses the server default. */
                        model?: (string | null) | undefined;
                        /** Ask the judge to reason step-by-step before answering. */
                        useCot?: boolean | undefined;
                    }

                    export namespace Judge {
                        export type ChoiceScores = ChoiceScores.Item[];

                        export namespace ChoiceScores {
                            /**
                             * One judge choice mapped to a numeric score, e.g. `A → 1.0`, `B → 0.5`, `C → 0.0`. When a judge scorer declares choices, the model must pick exactly one and the mapped score is the result.
                             */
                            export interface Item {
                                label: string;
                                score: number;
                            }
                        }
                    }

                    export const Kind = {
                        Rubric: "rubric",
                        Classifier: "classifier",
                        Metric: "metric",
                        Embedding: "embedding",
                        Assertion: "assertion",
                        Code: "code",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                    /** Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset"). */
                    export const Source = {
                        Proposed: "proposed",
                        Library: "library",
                        Custom: "custom",
                        Dataset: "dataset",
                    } as const;
                    export type Source = (typeof Source)[keyof typeof Source];
                    /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
                    export const Weight = {
                        Low: "low",
                        Med: "med",
                        High: "high",
                    } as const;
                    export type Weight = (typeof Weight)[keyof typeof Weight];
                }
            }
        }
    }

    export type Traces = Traces.Item[];

    export namespace Traces {
        export interface Item {
            addedAt?: (string | null) | undefined;
            addedBy?: (string | null) | undefined;
            clusterId?: (string | null) | undefined;
            durationMs: number;
            /** Pre-computed 2D embedding in normalized `[-1, 1]` space. */
            embedding?: (number[] | null) | undefined;
            eventCount: number;
            label: string;
            note?: (string | null) | undefined;
            primarySource: string;
            sources: string[];
            /** Train / validation / test split assignment. */
            split?: (Item.Split | null) | undefined;
            startedAt: string;
            /** Health status of a trace as judged by the dataset owner. */
            status: Item.Status;
            traceId: string;
        }

        export namespace Item {
            /** Train / validation / test split assignment. */
            export const Split = {
                Train: "train",
                Validation: "validation",
                Test: "test",
            } as const;
            export type Split = (typeof Split)[keyof typeof Split];
            /** Health status of a trace as judged by the dataset owner. */
            export const Status = {
                Ok: "ok",
                Warn: "warn",
                Error: "error",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
