// This file was auto-generated by Fern from our API Definition.

export interface TaskSuiteDetail {
    clusters: TaskSuiteDetail.Clusters.Item[];
    dataset: TaskSuiteDetail.Dataset;
    edges: TaskSuiteDetail.Edges.Item[];
}

export namespace TaskSuiteDetail {
    export type Clusters = Clusters.Item[];

    export namespace Clusters {
        export interface Item {
            /** CSS color for the cluster (e.g. `"var(--c-event-teal)"`). */
            color: string;
            description?: (string | null) | undefined;
            id: string;
            label: string;
            /** Optional pre-computed centroid hint in normalized [0..1] space. */
            similarityCenter?: (number[] | null) | undefined;
            traceIds: string[];
        }
    }

    export interface Dataset {
        /** Soft-archive timestamp. Present only when `includeArchived=true` or an archived Dataset is read directly. */
        archivedAt?: (string | null) | undefined;
        /** Display name of the dataset owner / creator. */
        createdBy?: (string | null) | undefined;
        description?: (string | null) | undefined;
        /** Optional total event count across all traces. */
        eventCount?: (number | null) | undefined;
        id: string;
        name: string;
        /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
        purpose?: (Dataset.Purpose | null) | undefined;
        /** Free-form pinned tags. */
        tags?: (string[] | null) | undefined;
        /** Number of traces currently in the dataset. */
        traceCount: number;
        /** ISO timestamp of the most recent addition. */
        updatedAt?: (string | null) | undefined;
    }

    export namespace Dataset {
        /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
        export const Purpose = {
            Eval: "eval",
            Training: "training",
            Replay: "replay",
            Review: "review",
        } as const;
        export type Purpose = (typeof Purpose)[keyof typeof Purpose];
    }

    export type Edges = Edges.Item[];

    export namespace Edges {
        export interface Item {
            fromTraceId: string;
            toTraceId: string;
            /** Similarity weight in [0..1]. */
            weight: number;
        }
    }
}
