// This file was auto-generated by Fern from our API Definition.

/**
 * One task in a dataset: the trace summary (its seed, when it has one), the stable membership identity used for lazy event reads and explicit refreshes, and the task definition with its verifier bindings.
 */
export interface Task {
    addedAt?: (string | null) | undefined;
    addedBy?: (string | null) | undefined;
    clusterId?: (string | null) | undefined;
    durationMs: number;
    /** Pre-computed 2D embedding in normalized `[-1, 1]` space. */
    embedding?: (number[] | null) | undefined;
    eventCount: number;
    label: string;
    membershipId: string;
    note?: (string | null) | undefined;
    primarySource: string;
    refreshAvailable: boolean;
    revision: number;
    sources: string[];
    /** Train / validation / test split assignment. */
    split?: (Task.Split | null) | undefined;
    startedAt: string;
    /** Health status of a trace as judged by the dataset owner. */
    status: Task.Status;
    subjectId: string;
    /** The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service. */
    subjectKind: Task.SubjectKind;
    /** What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`). */
    task?: Task.Task | undefined;
    traceId: string;
    verifiers?: Task.Verifiers.Item[] | undefined;
}

export namespace Task {
    /** Train / validation / test split assignment. */
    export const Split = {
        Train: "train",
        Validation: "validation",
        Test: "test",
    } as const;
    export type Split = (typeof Split)[keyof typeof Split];
    /** Health status of a trace as judged by the dataset owner. */
    export const Status = {
        Ok: "ok",
        Warn: "warn",
        Error: "error",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service. */
    export const SubjectKind = {
        Trace: "trace",
        Event: "event",
        Task: "task",
    } as const;
    export type SubjectKind = (typeof SubjectKind)[keyof typeof SubjectKind];

    /**
     * What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`).
     */
    export interface Task {
        /** Runtime knobs a task carries, mirroring the `[agent]`, `[verifier]` and `[environment]` tables of a Harbor `task.toml`. Every field is optional; the server policy fills defaults at launch. */
        config?: Task.Config | undefined;
        environmentId?: (string | null) | undefined;
        environmentVersionId?: (string | null) | undefined;
        /** What "done correctly" looks like. Passed to graders as the gold reference. For trace-seeded tasks this defaults to the events that followed the seed cutoff. */
        expectedOutcome?: unknown | undefined;
        /** The goal, as markdown. Harbor's `instruction.md`. */
        instruction?: (string | null) | undefined;
        /** Id of the last seed event. Events up to and including it are the context the agent sees; later events are the recorded outcome. */
        seedCutoffEventId?: (string | null) | undefined;
        /** Optional oracle: how a correct agent would solve this. Harbor's `solution/solve.sh` body. */
        solution?: (string | null) | undefined;
        /** Short human name. Defaults to the trace label for trace-seeded tasks. */
        title?: (string | null) | undefined;
    }

    export namespace Task {
        /**
         * Runtime knobs a task carries, mirroring the `[agent]`, `[verifier]` and `[environment]` tables of a Harbor `task.toml`. Every field is optional; the server policy fills defaults at launch.
         */
        export interface Config {
            agentTimeoutSec?: (number | null) | undefined;
            /** Network policy for the agent sandbox, mirroring Harbor's `[environment].network_mode`. */
            networkMode?: (Config.NetworkMode | null) | undefined;
            verifierTimeoutSec?: (number | null) | undefined;
        }

        export namespace Config {
            /** Network policy for the agent sandbox, mirroring Harbor's `[environment].network_mode`. */
            export const NetworkMode = {
                Public: "public",
                NoNetwork: "no-network",
            } as const;
            export type NetworkMode = (typeof NetworkMode)[keyof typeof NetworkMode];
        }
    }

    export type Verifiers = Verifiers.Item[];

    export namespace Verifiers {
        /**
         * One verifier bound to a task: a scorer from the tenant library plus the weight and pass threshold it carries for this task. Order is the position in the task's verifier list.
         */
        export interface Item {
            passThreshold?: (number | null) | undefined;
            scorerId: string;
            /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
            weight?: Item.Weight | undefined;
        }

        export namespace Item {
            /** Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray. */
            export const Weight = {
                Low: "low",
                Med: "med",
                High: "high",
            } as const;
            export type Weight = (typeof Weight)[keyof typeof Weight];
        }
    }
}
