// This file was auto-generated by Fern from our API Definition.

export interface TaskSuiteEvalRun {
    /** Display label — usually `agent.name@version` or a build hash. */
    agentLabel: string;
    /** Tasks that did not pass (see `task_results`). */
    failedTraceIds: string[];
    id: string;
    note?: (string | null) | undefined;
    /** 0–1; null while running. */
    passRate?: (number | null) | undefined;
    startedAt: string;
    /** Status badge tone for an eval run. */
    status: TaskSuiteEvalRun.Status;
    /** One entry per task whose trials have all finished. */
    taskResults?: TaskSuiteEvalRun.TaskResults.Item[] | undefined;
    totalCount: number;
}

export namespace TaskSuiteEvalRun {
    /** Status badge tone for an eval run. */
    export const Status = {
        Passing: "passing",
        Regressed: "regressed",
        Running: "running",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type TaskResults = TaskResults.Item[];

    export namespace TaskResults {
        /**
         * How one task fared in an eval run, aggregated over its trials.
         *
         * A task passes when every trial reached a terminal success and each verifier that declares a `passThreshold` scored at or above it.
         */
        export interface Item {
            /** Verifiers whose reward fell below their pass threshold (or was missing) in at least one trial. */
            failedVerifierIds?: string[] | undefined;
            passed: boolean;
            /** Mean of the top-level rewards across the task's trials; null when no trial recorded a reward. */
            score?: (number | null) | undefined;
            /** The task id (the membership subject id, which is also the case id). */
            traceId: string;
        }
    }
}
