// This file was auto-generated by Fern from our API Definition.

export interface TaskSuite {
    /** Soft-archive timestamp. Present only when `includeArchived=true` or an archived Dataset is read directly. */
    archivedAt?: (string | null) | undefined;
    /** Display name of the dataset owner / creator. */
    createdBy?: (string | null) | undefined;
    description?: (string | null) | undefined;
    /** Optional total event count across all traces. */
    eventCount?: (number | null) | undefined;
    id: string;
    name: string;
    /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
    purpose?: (TaskSuite.Purpose | null) | undefined;
    /** Free-form pinned tags. */
    tags?: (string[] | null) | undefined;
    /** Number of traces currently in the dataset. */
    traceCount: number;
    /** ISO timestamp of the most recent addition. */
    updatedAt?: (string | null) | undefined;
}

export namespace TaskSuite {
    /** Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue). */
    export const Purpose = {
        Eval: "eval",
        Training: "training",
        Replay: "replay",
        Review: "review",
    } as const;
    export type Purpose = (typeof Purpose)[keyof typeof Purpose];
}
