// This file was auto-generated by Fern from our API Definition.

export interface TaskEventPage {
    hasMore: boolean;
    items: TaskEventPage.Items.Item[];
    nextCursor?: (string | null) | undefined;
}

export namespace TaskEventPage {
    export type Items = Items.Item[];

    export namespace Items {
        /**
         * A single event rendered as a mark on the stream timeline. The full shape lives next to dataset shapes because `DatasetSnapshot.events` is the only consumer that ships over the wire today.
         */
        export interface Item {
            actor?: (string | null) | undefined;
            /** Optional explicit color override; falls back to the source color. */
            color?: (string | null) | undefined;
            /** Looser, app-defined grouping key (e.g. `conversation_id`). */
            correlationKey?: (string | null) | undefined;
            id: string;
            message?: (string | null) | undefined;
            /** ISO timestamp. */
            occurredAt: string;
            /** Direct causal predecessor. */
            parentEventId?: (string | null) | undefined;
            /** Raw payload — shown JSON-pretty in the detail panel. */
            payload?: unknown | undefined;
            /** Source/system the event came from (e.g. `intercom`, `stripe`). */
            source: string;
            /** Optional grouping (capture stream id) — currently informational. */
            stream?: (string | null) | undefined;
            /** Trace this event belongs to. */
            traceId?: (string | null) | undefined;
            /** Human-friendly label for the trace. */
            traceLabel?: (string | null) | undefined;
            /** Event type within the source (e.g. `conversation.created`). */
            type: string;
        }
    }
}
