// This file was auto-generated by Fern from our API Definition.

import type * as ChronicleLabsApi from "../index.js";

/**
 * Event emitted by the orchestrator on its broadcast channel; the SSE handler at `/api/platform/backtests/jobs/:id/stream` re-emits these to the dashboard + CLI. Variants match the dashboard's `BacktestsEvent` plus per-trial fine grain.
 */
export type TrialEvent =
    /**
     * The job moved into `running` (or back into `running` after a pause). */
    | ChronicleLabsApi.TrialEvent.JobStarted
    /**
     * A trial transitioned phases (queued → running → verifying → done). */
    | ChronicleLabsApi.TrialEvent.TrialPhaseChanged
    /**
     * A trial wrote a final reward set; the dashboard's metrics table updates incrementally. */
    | ChronicleLabsApi.TrialEvent.TrialRewardsRecorded
    /**
     * A trial reached a terminal status. */
    | ChronicleLabsApi.TrialEvent.TrialFinished
    /**
     * The job reached a terminal status. Carries a verdict so the list view can render without an extra fetch. */
    | ChronicleLabsApi.TrialEvent.JobFinished;

export namespace TrialEvent {
    export interface JobStarted {
        kind: "job-started";
        job_id: string;
    }

    export interface TrialPhaseChanged {
        kind: "trial-phase-changed";
        job_id: string;
        /** Phase of execution emitted on the SSE stream as the trial progresses. Distinct from `TrialStatus` — `TrialPhase` is fine-grained progress inside the lifecycle, `TrialStatus` is the persisted summary. */
        phase: TrialEventTrialPhaseChanged.Phase;
        trial_id: string;
    }

    export namespace TrialEventTrialPhaseChanged {
        /** Phase of execution emitted on the SSE stream as the trial progresses. Distinct from `TrialStatus` — `TrialPhase` is fine-grained progress inside the lifecycle, `TrialStatus` is the persisted summary. */
        export const Phase = {
            Queued: "queued",
            EnvironmentStart: "environment-start",
            EnvironmentReady: "environment-ready",
            AgentSetup: "agent-setup",
            AgentRunning: "agent-running",
            VerifierRunning: "verifier-running",
            ArtifactCollection: "artifact-collection",
            Cleanup: "cleanup",
            Done: "done",
        } as const;
        export type Phase = (typeof Phase)[keyof typeof Phase];
    }

    export interface TrialRewardsRecorded {
        kind: "trial-rewards-recorded";
        job_id: string;
        rewards: Record<string, number>;
        trial_id: string;
    }

    export interface TrialFinished {
        kind: "trial-finished";
        /** Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans. */
        exception?: (TrialEventTrialFinished.Exception | null) | undefined;
        job_id: string;
        /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
        status: TrialEventTrialFinished.Status;
        trial_id: string;
    }

    export namespace TrialEventTrialFinished {
        /**
         * Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans.
         */
        export interface Exception {
            kind: string;
            message: string;
        }

        /** Lifecycle state of a single `BacktestTrial` (one (case × agent) cell). */
        export const Status = {
            Pending: "pending",
            Setup: "setup",
            Running: "running",
            Verifying: "verifying",
            Succeeded: "succeeded",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }

    export interface JobFinished {
        kind: "job-finished";
        job_id: string;
        /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
        status: TrialEventJobFinished.Status;
        verdict?: (string | null) | undefined;
    }

    export namespace TrialEventJobFinished {
        /** Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`. */
        export const Status = {
            Pending: "pending",
            Running: "running",
            Succeeded: "succeeded",
            Failed: "failed",
            Cancelled: "cancelled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
