// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface QueryEventsRequest {
    source?: string;
    topic?: string;
    event_type?: string;
    entity_type?: string;
    entity_id?: string;
    /** Page size. Values above 200 are clamped to 200. */
    limit?: number;
    /** Opaque position returned as `next_cursor` by the preceding page. */
    cursor?: string;
    /** Relative time window, for example last_7d. */
    since?: string;
}
