// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface StreamEventsRequest {
    source?: string;
    event_type?: string;
    entity_type?: string;
    entity_id?: string;
    /** Opaque id from the last SSE message the client processed. */
    "Last-Event-ID"?: string;
}
