// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as ChronicleLabsApi from "../../../index.js";

export declare namespace LinksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Event and entity linking
 */
export class LinksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LinksClient.Options>;

    constructor(options: LinksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Requires scope events:write.
     *
     * @param {ChronicleLabsApi.AddEntityRefRequest} request
     * @param {LinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ChronicleLabsApi.BadRequestError}
     * @throws {@link ChronicleLabsApi.UnauthorizedError}
     * @throws {@link ChronicleLabsApi.ContentTooLargeError}
     * @throws {@link ChronicleLabsApi.UnsupportedMediaTypeError}
     * @throws {@link ChronicleLabsApi.UnprocessableEntityError}
     * @throws {@link ChronicleLabsApi.TooManyRequestsError}
     * @throws {@link ChronicleLabsApi.InternalServerError}
     * @throws {@link ChronicleLabsApi.ServiceUnavailableError}
     * @throws {@link ChronicleLabsApi.GatewayTimeoutError}
     * @throws {@link errors.ChronicleLabsApiError}
     * @throws {@link errors.ChronicleLabsApiTimeoutError}
     *
     * @example
     *     await client.links.addEntityRef({
     *         event_id: "event_id",
     *         entity_type: "entity_type",
     *         entity_id: "entity_id"
     *     })
     */
    public addEntityRef(
        request: ChronicleLabsApi.AddEntityRefRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): core.HttpResponsePromise<ChronicleLabsApi.StatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addEntityRef(request, requestOptions));
    }

    private async __addEntityRef(
        request: ChronicleLabsApi.AddEntityRefRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<ChronicleLabsApi.StatusResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronicleLabsApiEnvironment.Production,
                "v1/entity-refs",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ChronicleLabsApi.StatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ChronicleLabsApi.BadRequestError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new ChronicleLabsApi.UnauthorizedError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new ChronicleLabsApi.ContentTooLargeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new ChronicleLabsApi.UnsupportedMediaTypeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new ChronicleLabsApi.UnprocessableEntityError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new ChronicleLabsApi.TooManyRequestsError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ChronicleLabsApi.InternalServerError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new ChronicleLabsApi.ServiceUnavailableError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new ChronicleLabsApi.GatewayTimeoutError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronicleLabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/entity-refs");
    }

    /**
     * Requires scope events:write.
     *
     * @param {ChronicleLabsApi.CreateLinkRequest} request
     * @param {LinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ChronicleLabsApi.BadRequestError}
     * @throws {@link ChronicleLabsApi.UnauthorizedError}
     * @throws {@link ChronicleLabsApi.ContentTooLargeError}
     * @throws {@link ChronicleLabsApi.UnsupportedMediaTypeError}
     * @throws {@link ChronicleLabsApi.UnprocessableEntityError}
     * @throws {@link ChronicleLabsApi.TooManyRequestsError}
     * @throws {@link ChronicleLabsApi.InternalServerError}
     * @throws {@link ChronicleLabsApi.ServiceUnavailableError}
     * @throws {@link ChronicleLabsApi.GatewayTimeoutError}
     * @throws {@link errors.ChronicleLabsApiError}
     * @throws {@link errors.ChronicleLabsApiTimeoutError}
     *
     * @example
     *     await client.links.createEventLink({
     *         source_event_id: "source_event_id",
     *         target_event_id: "target_event_id",
     *         link_type: "link_type",
     *         confidence: 1.1
     *     })
     */
    public createEventLink(
        request: ChronicleLabsApi.CreateLinkRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): core.HttpResponsePromise<ChronicleLabsApi.CreateLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createEventLink(request, requestOptions));
    }

    private async __createEventLink(
        request: ChronicleLabsApi.CreateLinkRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<ChronicleLabsApi.CreateLinkResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronicleLabsApiEnvironment.Production,
                "v1/event-links",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ChronicleLabsApi.CreateLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ChronicleLabsApi.BadRequestError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new ChronicleLabsApi.UnauthorizedError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new ChronicleLabsApi.ContentTooLargeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new ChronicleLabsApi.UnsupportedMediaTypeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new ChronicleLabsApi.UnprocessableEntityError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new ChronicleLabsApi.TooManyRequestsError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ChronicleLabsApi.InternalServerError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new ChronicleLabsApi.ServiceUnavailableError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new ChronicleLabsApi.GatewayTimeoutError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronicleLabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/event-links");
    }

    /**
     * Requires scope events:write.
     *
     * @param {ChronicleLabsApi.LinkEntityRequest} request
     * @param {LinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ChronicleLabsApi.BadRequestError}
     * @throws {@link ChronicleLabsApi.UnauthorizedError}
     * @throws {@link ChronicleLabsApi.ContentTooLargeError}
     * @throws {@link ChronicleLabsApi.UnsupportedMediaTypeError}
     * @throws {@link ChronicleLabsApi.UnprocessableEntityError}
     * @throws {@link ChronicleLabsApi.TooManyRequestsError}
     * @throws {@link ChronicleLabsApi.InternalServerError}
     * @throws {@link ChronicleLabsApi.ServiceUnavailableError}
     * @throws {@link ChronicleLabsApi.GatewayTimeoutError}
     * @throws {@link errors.ChronicleLabsApiError}
     * @throws {@link errors.ChronicleLabsApiTimeoutError}
     *
     * @example
     *     await client.links.linkEntities({
     *         from_entity_type: "from_entity_type",
     *         from_entity_id: "from_entity_id",
     *         to_entity_type: "to_entity_type",
     *         to_entity_id: "to_entity_id"
     *     })
     */
    public linkEntities(
        request: ChronicleLabsApi.LinkEntityRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): core.HttpResponsePromise<ChronicleLabsApi.LinkEntityResponse> {
        return core.HttpResponsePromise.fromPromise(this.__linkEntities(request, requestOptions));
    }

    private async __linkEntities(
        request: ChronicleLabsApi.LinkEntityRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<ChronicleLabsApi.LinkEntityResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronicleLabsApiEnvironment.Production,
                "v1/link-entity",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ChronicleLabsApi.LinkEntityResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ChronicleLabsApi.BadRequestError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new ChronicleLabsApi.UnauthorizedError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new ChronicleLabsApi.ContentTooLargeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new ChronicleLabsApi.UnsupportedMediaTypeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new ChronicleLabsApi.UnprocessableEntityError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new ChronicleLabsApi.TooManyRequestsError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ChronicleLabsApi.InternalServerError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new ChronicleLabsApi.ServiceUnavailableError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new ChronicleLabsApi.GatewayTimeoutError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronicleLabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/link-entity");
    }

    /**
     * Requires scope events:read or events:write. The traversal is bounded by `max_depth`, is not cursor-paginated, and consumes 5 rate-limit units.
     *
     * @param {ChronicleLabsApi.GraphRequest} request
     * @param {LinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ChronicleLabsApi.BadRequestError}
     * @throws {@link ChronicleLabsApi.UnauthorizedError}
     * @throws {@link ChronicleLabsApi.ContentTooLargeError}
     * @throws {@link ChronicleLabsApi.UnsupportedMediaTypeError}
     * @throws {@link ChronicleLabsApi.UnprocessableEntityError}
     * @throws {@link ChronicleLabsApi.TooManyRequestsError}
     * @throws {@link ChronicleLabsApi.InternalServerError}
     * @throws {@link ChronicleLabsApi.ServiceUnavailableError}
     * @throws {@link ChronicleLabsApi.GatewayTimeoutError}
     * @throws {@link errors.ChronicleLabsApiError}
     * @throws {@link errors.ChronicleLabsApiTimeoutError}
     *
     * @example
     *     await client.links.traverseGraph({
     *         start_event_id: "start_event_id",
     *         direction: "outgoing"
     *     })
     */
    public traverseGraph(
        request: ChronicleLabsApi.GraphRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): core.HttpResponsePromise<ChronicleLabsApi.EventListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__traverseGraph(request, requestOptions));
    }

    private async __traverseGraph(
        request: ChronicleLabsApi.GraphRequest,
        requestOptions?: LinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<ChronicleLabsApi.EventListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ChronicleLabsApiEnvironment.Production,
                "v1/graph",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ChronicleLabsApi.EventListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ChronicleLabsApi.BadRequestError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new ChronicleLabsApi.UnauthorizedError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new ChronicleLabsApi.ContentTooLargeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 415:
                    throw new ChronicleLabsApi.UnsupportedMediaTypeError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new ChronicleLabsApi.UnprocessableEntityError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new ChronicleLabsApi.TooManyRequestsError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ChronicleLabsApi.InternalServerError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new ChronicleLabsApi.ServiceUnavailableError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new ChronicleLabsApi.GatewayTimeoutError(
                        _response.error.body as ChronicleLabsApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ChronicleLabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/graph");
    }
}
