// This file was auto-generated by Fern from our API Definition.

import * as ChronicleLabsApi from "../../src/api/index";
import { ChronicleLabsApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("listAgents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                capabilityTags: ["capabilityTags"],
                category: "category",
                description: "description",
                environment: "environment",
                framework: "vercel-ai-sdk",
                lastDriftAt: "2024-01-15T09:30:00Z",
                lastRunAt: "2024-01-15T09:30:00Z",
                latestVersion: "latestVersion",
                model: { label: "label", modelId: "modelId", provider: "provider" },
                modelLabel: "modelLabel",
                name: "name",
                owner: "owner",
                personaSummary: "personaSummary",
                playgroundUrl: "playgroundUrl",
                purpose: "purpose",
                runbookUrl: "runbookUrl",
                successRate: 1.1,
                totalRuns: 1,
                versionCount: 1,
            },
        ];

        server.mockEndpoint().get("/v1/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.listAgents();
        expect(response).toEqual(rawResponseBody);
    });

    test("listAgents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server.mockEndpoint().get("/v1/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.listAgents();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("searchAgentHashIndex (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                agentName: "agentName",
                artifactId: "artifactId",
                framework: "vercel-ai-sdk",
                hash: "hash",
                kind: "agent.root",
                observedAt: "2024-01-15T09:30:00Z",
                path: "path",
                preview: "preview",
                runId: "runId",
            },
        ];

        server
            .mockEndpoint()
            .get("/v1/agents/hash-index")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.searchAgentHashIndex();
        expect(response).toEqual(rawResponseBody);
    });

    test("searchAgentHashIndex (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/hash-index")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.searchAgentHashIndex();
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("searchAgentHashIndex (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/hash-index")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.searchAgentHashIndex();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("subscribeToAgentChanges (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = 'event: \ndata: {"key":"value"}\n\n';

        server
            .mockEndpoint()
            .get("/v1/agents/subscribe")
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.agents.subscribeToAgentChanges();
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                key: "value",
            },
        ]);
    });

    test("subscribeToAgentChanges (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/subscribe")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.subscribeToAgentChanges();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("updateAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            capabilityTags: ["capabilityTags"],
            category: "category",
            description: "description",
            environment: "environment",
            framework: "vercel-ai-sdk",
            lastDriftAt: "2024-01-15T09:30:00Z",
            lastRunAt: "2024-01-15T09:30:00Z",
            latestVersion: "latestVersion",
            model: { label: "label", modelId: "modelId", provider: "provider" },
            modelLabel: "modelLabel",
            name: "name",
            owner: "owner",
            personaSummary: "personaSummary",
            playgroundUrl: "playgroundUrl",
            purpose: "purpose",
            runbookUrl: "runbookUrl",
            successRate: 1.1,
            totalRuns: 1,
            versionCount: 1,
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgent({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("updateAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("updateAgent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/name")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("getAgentSnapshot (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hashIndex: [
                {
                    agentName: "agentName",
                    artifactId: "artifactId",
                    framework: "vercel-ai-sdk",
                    hash: "hash",
                    kind: "agent.root",
                    observedAt: "2024-01-15T09:30:00Z",
                    path: "path",
                    preview: "preview",
                    runId: "runId",
                },
            ],
            runs: [
                {
                    artifactId: "artifactId",
                    callOptionsHash: "callOptionsHash",
                    configHash: "configHash",
                    durationMs: 1,
                    error: { message: "message" },
                    finishedAt: "2024-01-15T09:30:00Z",
                    inputHash: "inputHash",
                    operation: "generate",
                    preparedCall: { hash: "hash" },
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
            ],
            summary: {
                capabilityTags: ["capabilityTags"],
                category: "category",
                description: "description",
                environment: "environment",
                framework: "vercel-ai-sdk",
                lastDriftAt: "2024-01-15T09:30:00Z",
                lastRunAt: "2024-01-15T09:30:00Z",
                latestVersion: "latestVersion",
                model: { label: "label", modelId: "modelId", provider: "provider" },
                modelLabel: "modelLabel",
                name: "name",
                owner: "owner",
                personaSummary: "personaSummary",
                playgroundUrl: "playgroundUrl",
                purpose: "purpose",
                runbookUrl: "runbookUrl",
                successRate: 1.1,
                totalRuns: 1,
                versionCount: 1,
            },
            versions: [
                {
                    artifact: {
                        artifactId: "artifactId",
                        configHash: "configHash",
                        framework: "vercel-ai-sdk",
                        model: { label: "label" },
                        name: "name",
                        provenance: { createdAt: "2024-01-15T09:30:00Z" },
                        schemaVersion: "schemaVersion",
                        tools: [{ name: "name" }],
                        version: "version",
                    },
                    lastRunAt: "2024-01-15T09:30:00Z",
                    meanDurationMs: 1,
                    p95DurationMs: 1,
                    resolvedModelIds: ["resolvedModelIds"],
                    runCount: 1,
                    status: "current",
                    successRate: 1.1,
                    totalTokens: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/snapshot")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgentSnapshot({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgentSnapshot (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/snapshot")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getAgentSnapshot({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("getAgentSnapshot (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/snapshot")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getAgentSnapshot({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("pinLatestAgentVersion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            capabilityTags: ["capabilityTags"],
            category: "category",
            description: "description",
            environment: "environment",
            framework: "vercel-ai-sdk",
            lastDriftAt: "2024-01-15T09:30:00Z",
            lastRunAt: "2024-01-15T09:30:00Z",
            latestVersion: "latestVersion",
            model: { label: "label", modelId: "modelId", provider: "provider" },
            modelLabel: "modelLabel",
            name: "name",
            owner: "owner",
            personaSummary: "personaSummary",
            playgroundUrl: "playgroundUrl",
            purpose: "purpose",
            runbookUrl: "runbookUrl",
            successRate: 1.1,
            totalRuns: 1,
            versionCount: 1,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/pin-latest")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.pinLatestAgentVersion({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("pinLatestAgentVersion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/pin-latest")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.pinLatestAgentVersion({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("pinLatestAgentVersion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/pin-latest")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.pinLatestAgentVersion({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("createAgentChatSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            session: {
                agentName: "agentName",
                agentVersion: "agentVersion",
                artifactId: "artifactId",
                messages: [{ messageId: "messageId", occurredAt: "2024-01-15T09:30:00Z", role: "user", text: "text" }],
                runId: "runId",
                sessionId: "sessionId",
                startedAt: "2024-01-15T09:30:00Z",
                traceId: "traceId",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.createAgentChatSession({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAgentChatSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgentChatSession({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("createAgentChatSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgentChatSession({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("createAgentChatSession (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgentChatSession({
                name: "name",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("getAgentChatSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            agentName: "agentName",
            agentVersion: "agentVersion",
            artifactId: "artifactId",
            messages: [
                {
                    error: "error",
                    eventIds: ["eventIds"],
                    messageId: "messageId",
                    occurredAt: "2024-01-15T09:30:00Z",
                    role: "user",
                    steps: [
                        {
                            eventType: "eventType",
                            source: "source",
                            stepId: "stepId",
                            text: "text",
                            toolName: "toolName",
                        },
                    ],
                    text: "text",
                },
            ],
            runId: "runId",
            sessionId: "sessionId",
            startedAt: "2024-01-15T09:30:00Z",
            traceId: "traceId",
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/chat/sessions/session_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgentChatSession({
            name: "name",
            session_id: "session_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgentChatSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/chat/sessions/session_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getAgentChatSession({
                name: "name",
                session_id: "session_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("getAgentChatSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/agents/name/chat/sessions/session_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.getAgentChatSession({
                name: "name",
                session_id: "session_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("sendAgentChatMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            session: {
                agentName: "agentName",
                agentVersion: "agentVersion",
                artifactId: "artifactId",
                messages: [{ messageId: "messageId", occurredAt: "2024-01-15T09:30:00Z", role: "user", text: "text" }],
                runId: "runId",
                sessionId: "sessionId",
                startedAt: "2024-01-15T09:30:00Z",
                traceId: "traceId",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions/session_id/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.sendAgentChatMessage({
            name: "name",
            session_id: "session_id",
            text: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("sendAgentChatMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions/session_id/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sendAgentChatMessage({
                name: "name",
                session_id: "session_id",
                text: "text",
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("sendAgentChatMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions/session_id/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sendAgentChatMessage({
                name: "name",
                session_id: "session_id",
                text: "text",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("sendAgentChatMessage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions/session_id/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sendAgentChatMessage({
                name: "name",
                session_id: "session_id",
                text: "text",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("sendAgentChatMessage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/name/chat/sessions/session_id/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sendAgentChatMessage({
                name: "name",
                session_id: "session_id",
                text: "text",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("registerAgentArtifact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            artifact: {
                artifactId: "artifactId",
                configHash: "configHash",
                framework: "vercel-ai-sdk",
                model: { label: "label" },
                name: "name",
                provenance: { createdAt: "2024-01-15T09:30:00Z" },
                schemaVersion: "schemaVersion",
                tools: [{ name: "name" }],
                version: "version",
            },
        };
        const rawResponseBody = {
            artifact: {
                artifactId: "artifactId",
                configHash: "configHash",
                description: "description",
                framework: "vercel-ai-sdk",
                inputContractPreview: { example: { key: "value" }, schemaSummary: "schemaSummary" },
                instructions: "instructions",
                instructionsHash: "instructionsHash",
                knowledgeSources: [{ id: "id", kind: "vector", label: "label" }],
                metadata: { key: "value" },
                model: { label: "label", modelId: "modelId", provider: "provider" },
                name: "name",
                outputContractPreview: { example: { key: "value" }, schemaSummary: "schemaSummary" },
                policy: {
                    allowedTools: ["allowedTools"],
                    approvalRequired: ["approvalRequired"],
                    maxSteps: 1,
                    metadata: { key: "value" },
                },
                provenance: {
                    aiSdkVersion: "aiSdkVersion",
                    createdAt: "2024-01-15T09:30:00Z",
                    dependencyLockHash: "dependencyLockHash",
                    frameworkVersion: "frameworkVersion",
                    gitSha: "gitSha",
                    publishedBy: "publishedBy",
                },
                providerOptions: { key: "value" },
                providerOptionsHash: "providerOptionsHash",
                schemaVersion: "schemaVersion",
                tools: [{ name: "name" }],
                version: "version",
                workflowGraphPreview: {
                    edges: [{ from: "from", to: "to" }],
                    nodes: [{ id: "id", kind: "input", label: "label" }],
                },
            },
            lastRunAt: "2024-01-15T09:30:00Z",
            meanDurationMs: 1,
            p95DurationMs: 1,
            resolvedModelIds: ["resolvedModelIds"],
            runCount: 1,
            status: "current",
            successRate: 1.1,
            totalTokens: 1,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/register")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.registerAgentArtifact({
            artifact: {
                artifactId: "artifactId",
                configHash: "configHash",
                framework: "vercel-ai-sdk",
                model: {
                    label: "label",
                },
                name: "name",
                provenance: {
                    createdAt: "2024-01-15T09:30:00Z",
                },
                schemaVersion: "schemaVersion",
                tools: [
                    {
                        name: "name",
                    },
                ],
                version: "version",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("registerAgentArtifact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            artifact: {
                artifactId: "artifactId",
                configHash: "configHash",
                framework: "vercel-ai-sdk",
                model: { label: "label" },
                name: "name",
                provenance: { createdAt: "2024-01-15T09:30:00Z" },
                schemaVersion: "schemaVersion",
                tools: [{ name: "name" }, { name: "name" }],
                version: "version",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/register")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.registerAgentArtifact({
                artifact: {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    framework: "vercel-ai-sdk",
                    model: {
                        label: "label",
                    },
                    name: "name",
                    provenance: {
                        createdAt: "2024-01-15T09:30:00Z",
                    },
                    schemaVersion: "schemaVersion",
                    tools: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                    version: "version",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("registerAgentArtifact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            artifact: {
                artifactId: "artifactId",
                configHash: "configHash",
                framework: "vercel-ai-sdk",
                model: { label: "label" },
                name: "name",
                provenance: { createdAt: "2024-01-15T09:30:00Z" },
                schemaVersion: "schemaVersion",
                tools: [{ name: "name" }, { name: "name" }],
                version: "version",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/register")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.registerAgentArtifact({
                artifact: {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    framework: "vercel-ai-sdk",
                    model: {
                        label: "label",
                    },
                    name: "name",
                    provenance: {
                        createdAt: "2024-01-15T09:30:00Z",
                    },
                    schemaVersion: "schemaVersion",
                    tools: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                    version: "version",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("recordAgentRuns (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            runs: [
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
            ],
        };
        const rawResponseBody = { accepted: 1 };

        server
            .mockEndpoint()
            .post("/v1/agents/runs/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.recordAgentRuns({
            runs: [
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("recordAgentRuns (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            runs: [
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
            ],
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/runs/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.recordAgentRuns({
                runs: [
                    {
                        artifactId: "artifactId",
                        configHash: "configHash",
                        operation: "generate",
                        runId: "runId",
                        schemaVersion: "schemaVersion",
                        startedAt: "2024-01-15T09:30:00Z",
                        status: "started",
                        toolCalls: [
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                        ],
                    },
                    {
                        artifactId: "artifactId",
                        configHash: "configHash",
                        operation: "generate",
                        runId: "runId",
                        schemaVersion: "schemaVersion",
                        startedAt: "2024-01-15T09:30:00Z",
                        status: "started",
                        toolCalls: [
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                        ],
                    },
                ],
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("recordAgentRuns (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            runs: [
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
                {
                    artifactId: "artifactId",
                    configHash: "configHash",
                    operation: "generate",
                    runId: "runId",
                    schemaVersion: "schemaVersion",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "started",
                    toolCalls: [
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                        {
                            callId: "callId",
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "started",
                            toolName: "toolName",
                        },
                    ],
                },
            ],
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "code",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/agents/runs/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.recordAgentRuns({
                runs: [
                    {
                        artifactId: "artifactId",
                        configHash: "configHash",
                        operation: "generate",
                        runId: "runId",
                        schemaVersion: "schemaVersion",
                        startedAt: "2024-01-15T09:30:00Z",
                        status: "started",
                        toolCalls: [
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                        ],
                    },
                    {
                        artifactId: "artifactId",
                        configHash: "configHash",
                        operation: "generate",
                        runId: "runId",
                        schemaVersion: "schemaVersion",
                        startedAt: "2024-01-15T09:30:00Z",
                        status: "started",
                        toolCalls: [
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                            {
                                callId: "callId",
                                startedAt: "2024-01-15T09:30:00Z",
                                status: "started",
                                toolName: "toolName",
                            },
                        ],
                    },
                ],
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });
});
