// This file was auto-generated by Fern from our API Definition.

import * as ChronicleLabsApi from "../../src/api/index";
import { ChronicleLabsApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BacktestsClient", () => {
    test("getBacktestsAvailability (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            agents: [
                {
                    capabilityTags: ["capabilityTags"],
                    category: "category",
                    description: "description",
                    environment: "environment",
                    framework: "vercel-ai-sdk",
                    lastDriftAt: "2024-01-15T09:30:00Z",
                    lastRunAt: "2024-01-15T09:30:00Z",
                    latestVersion: "latestVersion",
                    model: { label: "label" },
                    modelLabel: "modelLabel",
                    name: "name",
                    owner: "owner",
                    personaSummary: "personaSummary",
                    playgroundUrl: "playgroundUrl",
                    purpose: "purpose",
                    runbookUrl: "runbookUrl",
                    successRate: 1.1,
                    totalRuns: 1,
                    versionCount: 1,
                },
            ],
            datasetSnapshots: {
                key: {
                    clusters: [{ color: "color", id: "id", label: "label", traceIds: ["traceIds"] }],
                    dataset: { id: "id", name: "name", traceCount: 1 },
                    edges: [{ fromTraceId: "fromTraceId", toTraceId: "toTraceId", weight: 1.1 }],
                    events: [{ id: "id", occurredAt: "2024-01-15T09:30:00Z", source: "source", type: "type" }],
                    tasks: [
                        {
                            membershipId: "membershipId",
                            subjectKind: "trace",
                            task: {},
                            traceId: "traceId",
                            verifiers: [
                                { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                            ],
                        },
                    ],
                    traces: [
                        {
                            durationMs: 1,
                            eventCount: 1,
                            label: "label",
                            primarySource: "primarySource",
                            sources: ["sources"],
                            startedAt: "2024-01-15T09:30:00Z",
                            status: "ok",
                            traceId: "traceId",
                        },
                    ],
                },
            },
            datasets: [
                {
                    archivedAt: "2024-01-15T09:30:00Z",
                    createdBy: "createdBy",
                    description: "description",
                    eventCount: 1,
                    id: "id",
                    name: "name",
                    purpose: "eval",
                    tags: ["tags"],
                    traceCount: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            environments: [
                {
                    ephemeral: true,
                    id: "id",
                    label: "label",
                    snapshotId: "snapshotId",
                    snapshotLabel: "snapshotLabel",
                    status: "status",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/availability")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.getBacktestsAvailability();
        expect(response).toEqual(rawResponseBody);
    });

    test("getBacktestsAvailability (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/availability")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestsAvailability();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("getBacktestsAvailability (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/availability")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestsAvailability();
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("listBacktestJobs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            nextOffset: 1,
            runs: [
                {
                    agentIds: ["agentIds"],
                    datasetLabel: "datasetLabel",
                    divergences: 1,
                    environmentLabel: "environmentLabel",
                    hue: "hue",
                    id: "id",
                    mode: "replay",
                    name: "name",
                    owner: "owner",
                    scheduledFor: "2024-01-15T09:30:00Z",
                    status: "running",
                    totalRuns: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                    verdict: "verdict",
                },
            ],
        };

        server.mockEndpoint().get("/v1/backtests/jobs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.backtests.listBacktestJobs();
        expect(response).toEqual(rawResponseBody);
    });

    test("listBacktestJobs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server.mockEndpoint().get("/v1/backtests/jobs").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.backtests.listBacktestJobs();
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("listBacktestJobs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server.mockEndpoint().get("/v1/backtests/jobs").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.backtests.listBacktestJobs();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("createBacktestJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            recipe: {
                agents: [{ hue: "hue", id: "id", label: "label", notes: "notes" }],
                data: {
                    kind: "composed",
                    scenarios: [{ count: 1, id: "id", kind: "adversarial", label: "label" }],
                    sources: [{ count: 1, id: "id", kind: "prod", label: "label" }],
                },
                graders: [{ id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" }],
                mode: "replay",
                name: "name",
            },
        };
        const rawResponseBody = {
            jobId: "jobId",
            run: {
                agentIds: ["agentIds"],
                datasetLabel: "datasetLabel",
                divergences: 1,
                environmentLabel: "environmentLabel",
                hue: "hue",
                id: "id",
                mode: "replay",
                name: "name",
                owner: "owner",
                scheduledFor: "2024-01-15T09:30:00Z",
                status: "running",
                totalRuns: 1,
                updatedAt: "2024-01-15T09:30:00Z",
                verdict: "verdict",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.createBacktestJob({
            name: "name",
            recipe: {
                agents: [
                    {
                        hue: "hue",
                        id: "id",
                        label: "label",
                        notes: "notes",
                    },
                ],
                data: {
                    kind: "composed",
                    scenarios: [
                        {
                            count: 1,
                            id: "id",
                            kind: "adversarial",
                            label: "label",
                        },
                    ],
                    sources: [
                        {
                            count: 1,
                            id: "id",
                            kind: "prod",
                            label: "label",
                        },
                    ],
                },
                graders: [
                    {
                        id: "id",
                        kind: "rubric",
                        label: "label",
                        source: "proposed",
                        weight: "low",
                    },
                ],
                mode: "replay",
                name: "name",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createBacktestJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            recipe: {
                agents: [
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                ],
                data: {
                    kind: "composed",
                    scenarios: [
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                    ],
                    sources: [
                        { count: 1, id: "id", kind: "prod", label: "label" },
                        { count: 1, id: "id", kind: "prod", label: "label" },
                    ],
                },
                graders: [
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                ],
                mode: "replay",
                name: "name",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.createBacktestJob({
                name: "name",
                recipe: {
                    agents: [
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                    ],
                    data: {
                        kind: "composed",
                        scenarios: [
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                        ],
                        sources: [
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                        ],
                    },
                    graders: [
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                    ],
                    mode: "replay",
                    name: "name",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("createBacktestJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            recipe: {
                agents: [
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                ],
                data: {
                    kind: "composed",
                    scenarios: [
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                    ],
                    sources: [
                        { count: 1, id: "id", kind: "prod", label: "label" },
                        { count: 1, id: "id", kind: "prod", label: "label" },
                    ],
                },
                graders: [
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                ],
                mode: "replay",
                name: "name",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.createBacktestJob({
                name: "name",
                recipe: {
                    agents: [
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                    ],
                    data: {
                        kind: "composed",
                        scenarios: [
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                        ],
                        sources: [
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                        ],
                    },
                    graders: [
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                    ],
                    mode: "replay",
                    name: "name",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("createBacktestJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            recipe: {
                agents: [
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                ],
                data: {
                    kind: "composed",
                    scenarios: [
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                    ],
                    sources: [
                        { count: 1, id: "id", kind: "prod", label: "label" },
                        { count: 1, id: "id", kind: "prod", label: "label" },
                    ],
                },
                graders: [
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                ],
                mode: "replay",
                name: "name",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.createBacktestJob({
                name: "name",
                recipe: {
                    agents: [
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                    ],
                    data: {
                        kind: "composed",
                        scenarios: [
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                        ],
                        sources: [
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                        ],
                    },
                    graders: [
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                    ],
                    mode: "replay",
                    name: "name",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.ConflictError);
    });

    test("createBacktestJob (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            recipe: {
                agents: [
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                    { hue: "hue", id: "id", label: "label", notes: "notes" },
                ],
                data: {
                    kind: "composed",
                    scenarios: [
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                        { count: 1, id: "id", kind: "adversarial", label: "label" },
                    ],
                    sources: [
                        { count: 1, id: "id", kind: "prod", label: "label" },
                        { count: 1, id: "id", kind: "prod", label: "label" },
                    ],
                },
                graders: [
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                    { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                ],
                mode: "replay",
                name: "name",
            },
        };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.createBacktestJob({
                name: "name",
                recipe: {
                    agents: [
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                        {
                            hue: "hue",
                            id: "id",
                            label: "label",
                            notes: "notes",
                        },
                    ],
                    data: {
                        kind: "composed",
                        scenarios: [
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "adversarial",
                                label: "label",
                            },
                        ],
                        sources: [
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                            {
                                count: 1,
                                id: "id",
                                kind: "prod",
                                label: "label",
                            },
                        ],
                    },
                    graders: [
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                        {
                            id: "id",
                            kind: "rubric",
                            label: "label",
                            source: "proposed",
                            weight: "low",
                        },
                    ],
                    mode: "replay",
                    name: "name",
                },
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("getBacktestJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job: {
                completedTrials: 1,
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "createdBy",
                datasetId: "datasetId",
                datasetVersionId: "datasetVersionId",
                exceptionKind: "exceptionKind",
                failedTrials: 1,
                finishedAt: "2024-01-15T09:30:00Z",
                id: "id",
                mode: "replay",
                nConcurrent: 1,
                name: "name",
                recipe: { key: "value" },
                retryConfig: {
                    excludeExceptions: ["excludeExceptions"],
                    includeExceptions: ["includeExceptions"],
                    maxRetries: 1,
                    maxWaitSec: 1.1,
                    minWaitSec: 1.1,
                    waitMultiplier: 1.1,
                },
                sandboxDriver: "docker",
                scheduledFor: "2024-01-15T09:30:00Z",
                startedAt: "2024-01-15T09:30:00Z",
                status: "pending",
                tenantId: "tenantId",
                totalTrials: 1,
                updatedAt: "2024-01-15T09:30:00Z",
                verdict: "verdict",
            },
            run: {
                agentIds: ["agentIds"],
                datasetLabel: "datasetLabel",
                divergences: 1,
                environmentLabel: "environmentLabel",
                hue: "hue",
                id: "id",
                mode: "replay",
                name: "name",
                owner: "owner",
                scheduledFor: "2024-01-15T09:30:00Z",
                status: "running",
                totalRuns: 1,
                updatedAt: "2024-01-15T09:30:00Z",
                verdict: "verdict",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.getBacktestJob({
            job_id: "job_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBacktestJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestJob({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("getBacktestJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestJob({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("listBacktestJobTrials (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            nextOffset: 1,
            rewards: { key: { key: 1.1 } },
            trials: [
                {
                    agentId: "agentId",
                    agentLabel: "agentLabel",
                    attempt: 1,
                    caseCluster: "caseCluster",
                    caseId: "caseId",
                    createdAt: "2024-01-15T09:30:00Z",
                    durationMs: 1,
                    exception: { kind: "kind", message: "message" },
                    id: "id",
                    instruction: "instruction",
                    isBaseline: true,
                    jobId: "jobId",
                    sandboxId: "sandboxId",
                    status: "pending",
                    tenantId: "tenantId",
                    timings: {},
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.listBacktestJobTrials({
            job_id: "job_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listBacktestJobTrials (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.listBacktestJobTrials({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("listBacktestJobTrials (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.listBacktestJobTrials({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("listBacktestJobTrials (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.listBacktestJobTrials({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("getBacktestTrial (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            artifacts: [
                {
                    contentType: "contentType",
                    createdAt: "2024-01-15T09:30:00Z",
                    id: "id",
                    kind: "agent-log",
                    path: "path",
                    sizeBytes: 1000000,
                    trialId: "trialId",
                },
            ],
            rewards: { key: 1.1 },
            scorers: [
                {
                    grader: { id: "id", kind: "rubric", label: "label", source: "proposed", weight: "low" },
                    rewardKey: "rewardKey",
                },
            ],
            steps: [
                {
                    actor: "environment",
                    createdAt: "2024-01-15T09:30:00Z",
                    endedAt: "2024-01-15T09:30:00Z",
                    graderId: "graderId",
                    id: "id",
                    kind: "seed-event",
                    ordinal: 1,
                    payload: { key: "value" },
                    score: 1.1,
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "ok",
                    title: "title",
                    trialId: "trialId",
                },
            ],
            trial: {
                agentId: "agentId",
                agentLabel: "agentLabel",
                attempt: 1,
                caseCluster: "caseCluster",
                caseId: "caseId",
                createdAt: "2024-01-15T09:30:00Z",
                durationMs: 1,
                exception: { kind: "kind", message: "message" },
                id: "id",
                instruction: "instruction",
                isBaseline: true,
                jobId: "jobId",
                sandboxId: "sandboxId",
                status: "pending",
                tenantId: "tenantId",
                timings: {
                    agentRunFinishedAt: "2024-01-15T09:30:00Z",
                    agentRunStartedAt: "2024-01-15T09:30:00Z",
                    agentSetupFinishedAt: "2024-01-15T09:30:00Z",
                    agentSetupStartedAt: "2024-01-15T09:30:00Z",
                    envSetupFinishedAt: "2024-01-15T09:30:00Z",
                    envSetupStartedAt: "2024-01-15T09:30:00Z",
                    verifierFinishedAt: "2024-01-15T09:30:00Z",
                    verifierStartedAt: "2024-01-15T09:30:00Z",
                },
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials/trial_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.getBacktestTrial({
            job_id: "job_id",
            trial_id: "trial_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBacktestTrial (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials/trial_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestTrial({
                job_id: "job_id",
                trial_id: "trial_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("getBacktestTrial (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/trials/trial_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.getBacktestTrial({
                job_id: "job_id",
                trial_id: "trial_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("cancelBacktestJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { aborted: true, jobId: "jobId", previousStatus: "pending" };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs/job_id/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.backtests.cancelBacktestJob({
            job_id: "job_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancelBacktestJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs/job_id/cancel")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.cancelBacktestJob({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("cancelBacktestJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs/job_id/cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.cancelBacktestJob({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("cancelBacktestJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/backtests/jobs/job_id/cancel")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.cancelBacktestJob({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("streamBacktestJobEvents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = 'event: \ndata: {"job_id":"job_id","kind":"job-started"}\n\n';

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/stream")
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.backtests.streamBacktestJobEvents({
            job_id: "job_id",
        });
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                kind: "job-started",
                job_id: "job_id",
            },
        ]);
    });

    test("streamBacktestJobEvents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/stream")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.streamBacktestJobEvents({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("streamBacktestJobEvents (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/stream")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.streamBacktestJobEvents({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });

    test("streamBacktestJobEvents (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .get("/v1/backtests/jobs/job_id/stream")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.backtests.streamBacktestJobEvents({
                job_id: "job_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });
});
