// This file was auto-generated by Fern from our API Definition.

import * as ChronicleLabsApi from "../../src/api/index";
import { ChronicleLabsApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CredentialsClient", () => {
    test("listSdkKeys (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            keys: [
                {
                    createdAt: "2024-01-15T09:30:00Z",
                    id: "id",
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    name: "name",
                    prefix: "prefix",
                    revokedAt: "2024-01-15T09:30:00Z",
                    scopes: ["scopes"],
                    tenantId: "tenantId",
                },
            ],
        };

        server.mockEndpoint().get("/v1/sdk-keys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.credentials.listSdkKeys();
        expect(response).toEqual(rawResponseBody);
    });

    test("listSdkKeys (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server.mockEndpoint().get("/v1/sdk-keys").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.credentials.listSdkKeys();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("createSdkKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", scopes: ["traces:write"] };
        const rawResponseBody = {
            createdAt: "2024-01-15T09:30:00Z",
            id: "id",
            lastUsedAt: "2024-01-15T09:30:00Z",
            name: "name",
            prefix: "prefix",
            revokedAt: "2024-01-15T09:30:00Z",
            scopes: ["scopes"],
            tenantId: "tenantId",
            bearer: "bearer",
        };

        server
            .mockEndpoint()
            .post("/v1/sdk-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.credentials.createSdkKey({
            name: "name",
            scopes: ["traces:write"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createSdkKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x", scopes: ["traces:write", "traces:write"] };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/sdk-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.credentials.createSdkKey({
                name: "x",
                scopes: ["traces:write", "traces:write"],
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("createSdkKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x", scopes: ["traces:write", "traces:write"] };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/sdk-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.credentials.createSdkKey({
                name: "x",
                scopes: ["traces:write", "traces:write"],
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("revokeSdkKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/sdk-keys/key_id").respondWith().statusCode(200).build();

        const response = await client.credentials.revokeSdkKey({
            key_id: "key_id",
        });
        expect(response).toEqual(undefined);
    });

    test("revokeSdkKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .delete("/v1/sdk-keys/key_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.credentials.revokeSdkKey({
                key_id: "key_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("revokeSdkKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .delete("/v1/sdk-keys/key_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.credentials.revokeSdkKey({
                key_id: "key_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.NotFoundError);
    });
});
