// This file was auto-generated by Fern from our API Definition.

import * as ChronicleLabsApi from "../../src/api/index";
import { ChronicleLabsApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SdkClient", () => {
    test("identifyUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = { accepted: 1 };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sdk.identifyUser({
            user_id: "user_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("identifyUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("identifyUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("identifyUser (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.ContentTooLargeError);
    });

    test("identifyUser (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnsupportedMediaTypeError);
    });

    test("identifyUser (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnprocessableEntityError);
    });

    test("identifyUser (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.TooManyRequestsError);
    });

    test("identifyUser (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.InternalServerError);
    });

    test("identifyUser (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("identifyUser (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/users/identify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.identifyUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ChronicleLabsApi.GatewayTimeoutError);
    });

    test("trackSignals (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { accepted: 1 };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sdk.trackSignals();
        expect(response).toEqual(rawResponseBody);
    });

    test("trackSignals (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("trackSignals (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("trackSignals (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.ContentTooLargeError);
    });

    test("trackSignals (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.UnsupportedMediaTypeError);
    });

    test("trackSignals (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.UnprocessableEntityError);
    });

    test("trackSignals (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.TooManyRequestsError);
    });

    test("trackSignals (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.InternalServerError);
    });

    test("trackSignals (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("trackSignals (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/signals/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackSignals();
        }).rejects.toThrow(ChronicleLabsApi.GatewayTimeoutError);
    });

    test("trackTraces (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { accepted: 1 };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sdk.trackTraces();
        expect(response).toEqual(rawResponseBody);
    });

    test("trackTraces (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("trackTraces (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("trackTraces (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.ContentTooLargeError);
    });

    test("trackTraces (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.UnsupportedMediaTypeError);
    });

    test("trackTraces (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.UnprocessableEntityError);
    });

    test("trackTraces (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.TooManyRequestsError);
    });

    test("trackTraces (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.InternalServerError);
    });

    test("trackTraces (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("trackTraces (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/traces/track")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sdk.trackTraces();
        }).rejects.toThrow(ChronicleLabsApi.GatewayTimeoutError);
    });
});
