// This file was auto-generated by Fern from our API Definition.

import * as ChronicleLabsApi from "../../src/api/index";
import { ChronicleLabsApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            data: [
                {
                    event: {
                        event_id: "evt_18C8B8D284059DAF4a74c7cc2a3a669d",
                        org_id: "org_id",
                        source: "stripe",
                        topic: "payments",
                        event_type: "payment_intent.succeeded",
                        event_time: "2024-01-15T09:30:00Z",
                        ingestion_time: "2024-01-15T09:30:00Z",
                        media: { media_type: "image/jpeg", size_bytes: 1000000 },
                        entity_refs: [{ entity_type: "customer", entity_id: "cust_123" }],
                    },
                    entity_refs: [
                        {
                            event_id: "event_id",
                            entity_type: "customer",
                            entity_id: "cust_123",
                            created_by: "ingestion",
                            created_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                    search_distance: 1.1,
                },
            ],
            next_cursor: "next_cursor",
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.search.events({
            query: "query",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.BadRequestError);
    });

    test("events (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnauthorizedError);
    });

    test("events (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.ContentTooLargeError);
    });

    test("events (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnsupportedMediaTypeError);
    });

    test("events (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.UnprocessableEntityError);
    });

    test("events (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.TooManyRequestsError);
    });

    test("events (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.InternalServerError);
    });

    test("events (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.ServiceUnavailableError);
    });

    test("events (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new ChronicleLabsApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            type: "type",
            title: "title",
            status: 1,
            detail: "detail",
            code: "not_found",
            error: "error",
            message: "message",
            retryable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.search.events({
                query: "query",
            });
        }).rejects.toThrow(ChronicleLabsApi.GatewayTimeoutError);
    });
});
