// This file was auto-generated by Fern from our API Definition.

import { DiscoverClient } from "./api/resources/discover/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { LinksClient } from "./api/resources/links/client/Client.js";
import { SdkClient } from "./api/resources/sdk/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { TimelineClient } from "./api/resources/timeline/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ChronicleLabsApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ChronicleLabsApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ChronicleLabsApiClient.Options>;
    protected _events: EventsClient | undefined;
    protected _timeline: TimelineClient | undefined;
    protected _search: SearchClient | undefined;
    protected _discover: DiscoverClient | undefined;
    protected _links: LinksClient | undefined;
    protected _sdk: SdkClient | undefined;

    constructor(options: ChronicleLabsApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get timeline(): TimelineClient {
        return (this._timeline ??= new TimelineClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get discover(): DiscoverClient {
        return (this._discover ??= new DiscoverClient(this._options));
    }

    public get links(): LinksClient {
        return (this._links ??= new LinksClient(this._options));
    }

    public get sdk(): SdkClient {
        return (this._sdk ??= new SdkClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
