// This file was auto-generated by Fern from our API Definition.

export const ChronicleLabsApiEnvironment = {
    Production: "https://api.chroniclelabs.ai",
} as const;

export type ChronicleLabsApiEnvironment = typeof ChronicleLabsApiEnvironment.Production;
