// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface IdentifyUserRequest {
    user_id: string;
    traits?: Record<string, unknown>;
}
